  // src/mock_products.js
const MOCK_PRODUCTS = [
{ id: "p1", name: "Adidas 700 V3 Azael For Her", price: 6200, rating: 4.3, category: "Women’s Kick", image: "/src/assets/products/p1.jpg" },
{ id: "p2", name: "Air Jordan 1 Mid Magenta For Women", price: 6800, rating: 4.4, category: "Women’s Kick", image: "/src/assets/products/p2.jpg" },
{ id: "p3", name: "Air Jordan Retro 1 Mid GS White Dior", price: 7200, rating: 4.5, category: "Women’s Kick", image: "/src/assets/products/p3.jpg" },
{ id: "p4", name: "Air Jordan Retro 4 Off-White", price: 7999, rating: 4.6, category: "Women’s Kick", image: "/src/assets/products/p4.jpg" },
{ id: "p5", name: "Airmax Pink 2090 Womens", price: 5800, rating: 4.2, category: "Women’s Kick", image: "/src/assets/products/p5.jpg" },
{ id: "p6", name: "Dior X Air Jordan 1 High Premium", price: 9500, rating: 4.7, category: "Women’s Kick", image: "/src/assets/products/p6.jpg" },
{ id: "p7", name: "Nike Cortez Baroque Brown W", price: 5600, rating: 4.1, category: "Women’s Kick", image: "/src/assets/products/p7.jpg" },
{ id: "p8", name: "New Balance 327 Multi", price: 6999, rating: 4.4, category: "Women’s Kick", image: "/src/assets/products/p8.jpg" },
  //{ id: "p9", name: "Women’s Kick 9", price: 1600, rating: 4.1, category: "Women’s Kick", image: "/src/assets/products/p9.jpg" },
  //{ id: "p10", name: "Women’s Kick 10", price: 1500, rating: 4.2, category: "Women’s Kick", image: "/src/assets/products/p10.jpg" },
  { id: "p11", name: "Men’s Kick 1", price: 650, rating: 4.3, category: "Men’s Kick", image: "/src/assets/products/p11.jpg" },
  { id: "p12", name: "Men’s Kick 2", price: 800, rating: 4.4, category: "Men’s Kick", image: "/src/assets/products/p12.jpg" },
  { id: "p13", name: "Men’s Kick 3", price: 950, rating: 4.5, category: "Men’s Kick", image: "/src/assets/products/p13.jpg" },
  { id: "p14", name: "Men’s Kick 4", price: 1100, rating: 4.6, category: "Men’s Kick", image: "/src/assets/products/p14.jpg" },
  { id: "p15", name: "Men’s Kick 5", price: 1000, rating: 4.7, category: "Men’s Kick", image: "/src/assets/products/p15.jpg" },
  { id: "p16", name: "Men’s Kick 6", price: 1150, rating: 4.0, category: "Men’s Kick", image: "/src/assets/products/p16.jpg" },
  { id: "p17", name: "Men’s Kick 7", price: 1300, rating: 4.1, category: "Men’s Kick", image: "/src/assets/products/p17.jpg" },
  { id: "p18", name: "Men’s Kick 8", price: 1450, rating: 4.2, category: "Men’s Kick", image: "/src/assets/products/p18.jpg" },
  //{ id: "p19", name: "Men’s Kick 9", price: 1600, rating: 4.3, category: "Men’s Kick", image: "/src/assets/products/p19.jpg" },
  //{ id: "p20", name: "Men’s Kick 10", price: 1500, rating: 4.4, category: "Men’s Kick", image: "/src/assets/products/p20.jpg" },

{ id: "p21", name: "Louis Vuitton Monogram Canvas Wallet", price: 6500, rating: 4.7, category: "Wallet", image: "/src/assets/products/p21.jpg" },
{ id: "p22", name: "Gucci GG Marmont Leather Wallet", price: 7200, rating: 4.8, category: "Wallet", image: "/src/assets/products/p22.jpg" },
{ id: "p23", name: "Fossil Derrick Leather Bifold Wallet", price: 3200, rating: 4.5, category: "Wallet", image: "/src/assets/products/p23.jpg" },
{ id: "p24", name: "Tommy Hilfiger Slim Leather Wallet", price: 2800, rating: 4.4, category: "Wallet", image: "/src/assets/products/p24.jpg" },
{ id: "p25", name: "Montblanc Sartorial Leather Wallet", price: 8500, rating: 4.9, category: "Wallet", image: "/src/assets/products/p25.jpg" },
{ id: "p26", name: "WildHorn Genuine Leather Wallet", price: 1800, rating: 4.3, category: "Wallet", image: "/src/assets/products/p26.jpg" },
{ id: "p27", name: "Allen Solly Brown Textured Wallet", price: 2200, rating: 4.2, category: "Wallet", image: "/src/assets/products/p27.jpg" },
{ id: "p28", name: "Coach Signature Compact Wallet", price: 5400, rating: 4.6, category: "Wallet", image: "/src/assets/products/p28.jpg" },
{ id: "p29", name: "Calvin Klein Black Leather Wallet", price: 3500, rating: 4.5, category: "Wallet", image: "/src/assets/products/p29.jpg" },
{ id: "p30", name: "Hidesign Classic Tan Wallet", price: 3000, rating: 4.4, category: "Wallet", image: "/src/assets/products/p30.jpg" },
  { id: "p2221", name: "Leather Bi-Fold Wallet", price: 1700, rating: 4.4, category: "Wallet", image: "/src/assets/products/p2221.jpg" },
  { id: "p2222", name: "Classic Slim Wallet", price: 1400, rating: 4.3, category: "Wallet", image: "/src/assets/products/p2222.jpg" },
  { id: "p2223", name: "Luxury Designer Wallet", price: 2100, rating: 4.6, category: "Wallet", image: "/src/assets/products/p2223.jpg" },
   { id: "p2224", name: "Casual Brown Wallet", price: 1300, rating: 4.2, category: "Wallet", image: "/src/assets/products/p2224.jpg" },
  { id: "p2225", name: "Premium Leather Wallet", price: 2500, rating: 4.7, category: "Wallet", image: "/src/assets/products/p2225.jpg" },
  { id: "p2226", name: "Carbon Fiber Slim Wallet", price: 1900, rating: 4.5, category: "Wallet", image: "/src/assets/products/p2226.jpg" },


{ id: "p31", name: "Gucci GG Supreme Leather Belt", price: 8500, rating: 4.8, category: "Belt", image: "/src/assets/products/p31.jpg" },
{ id: "p32", name: "Louis Vuitton Initiales Monogram Belt", price: 9500, rating: 4.9, category: "Belt", image: "/src/assets/products/p32.jpg" },
{ id: "p33", name: "Hermès H Buckle Leather Belt", price: 12000, rating: 5.0, category: "Belt", image: "/src/assets/products/p33.jpg" },
{ id: "p34", name: "Armani Exchange Black Leather Belt", price: 4200, rating: 4.5, category: "Belt", image: "/src/assets/products/p34.jpg" },
{ id: "p35", name: "Calvin Klein Reversible Buckle Belt", price: 3800, rating: 4.4, category: "Belt", image: "/src/assets/products/p35.jpg" },
{ id: "p36", name: "Tommy Hilfiger Casual Brown Belt", price: 3200, rating: 4.3, category: "Belt", image: "/src/assets/products/p36.jpg" },
{ id: "p37", name: "Diesel Logo Engraved Leather Belt", price: 4000, rating: 4.6, category: "Belt", image: "/src/assets/products/p37.jpg" },
{ id: "p38", name: "Versace Medusa Buckle Belt", price: 11000, rating: 4.9, category: "Belt", image: "/src/assets/products/p38.jpg" },
{ id: "p39", name: "BOSS Hugo Reversible Leather Belt", price: 5000, rating: 4.5, category: "Belt", image: "/src/assets/products/p39.jpg" },
{ id: "p40", name: "Fossil Classic Black Leather Belt", price: 2800, rating: 4.2, category: "Belt", image: "/src/assets/products/p40.jpg" },
{ id: "p3331", name: "Montblanc Sartorial Leather Belt", price: 9700, rating: 4.8, category: "Belt", image: "/src/assets/products/p3331.jpg" },
{ id: "p3332", name: "WildHorn Genuine Leather Belt", price: 1900, rating: 4.1, category: "Belt", image: "/src/assets/products/p3332.jpg" },
{ id: "p3333", name: "Allen Solly Formal Brown Belt", price: 2500, rating: 4.2, category: "Belt", image: "/src/assets/products/p3333.jpg" },
{ id: "p3334", name: "Woodland Outdoor Rugged Belt", price: 2200, rating: 4.3, category: "Belt", image: "/src/assets/products/p3334.jpg" },
{ id: "p3335", name: "Prada Saffiano Leather Belt", price: 11500, rating: 5.0, category: "Belt", image: "/src/assets/products/p3335.jpg" },
{ id: "p3336", name: "Coach Signature Buckle Belt", price: 6200, rating: 4.6, category: "Belt", image: "/src/assets/products/p3336.jpg" },
{ id: "p3337", name: "Salvatore Ferragamo Gancini Belt", price: 9800, rating: 4.9, category: "Belt", image: "/src/assets/products/p3337.jpg" },
{ id: "p3338", name: "Burberry London Leather Check Belt", price: 8900, rating: 4.8, category: "Belt", image: "/src/assets/products/p3338.jpg" },


// --- Hand Bags (p41 to p50) ---
{ id: "p41", name: "Michael Kors Jet Set Leather Tote", price: 9500, rating: 4.8, category: "Hand Bag", image: "/src/assets/products/p41.jpg" },
  { id: "p42", name: "Coach Tabby Shoulder Bag 26", price: 10500, rating: 4.7, category: "Hand Bag", image: "/src/assets/products/p42.png" },
{ id: "p43", name: "Tory Burch Perry Triple-Compartment Tote", price: 11200, rating: 4.8, category: "Hand Bag", image: "/src/assets/products/p43.jpg" },
{ id: "p44", name: "Kate Spade Margaux Medium Satchel", price: 8800, rating: 4.6, category: "Hand Bag", image: "/src/assets/products/p44.jpg" },
{ id: "p45", name: "Guess Alby Crossbody Flap", price: 5600, rating: 4.5, category: "Hand Bag", image: "/src/assets/products/p45.jpg" },
{ id: "p46", name: "Charles & Keith Quilted Top Handle Bag", price: 6300, rating: 4.5, category: "Hand Bag", image: "/src/assets/products/p46.jpg" },
{ id: "p47", name: "Fossil Fiona Leather Satchel", price: 7200, rating: 4.6, category: "Hand Bag", image: "/src/assets/products/p47.jpg" },
{ id: "p48", name: "ALDO Barland Structured Handbag", price: 4800, rating: 4.3, category: "Hand Bag", image: "/src/assets/products/p48.jpg" },
{ id: "p49", name: "Calvin Klein Monogram Crossbody", price: 5900, rating: 4.4, category: "Hand Bag", image: "/src/assets/products/p49.jpg" },
{ id: "p50", name: "Baggit Earthy Tan Vegan Tote", price: 4600, rating: 4.2, category: "Hand Bag", image: "/src/assets/products/p50.jpg" },
{ id: "p4441", name: "Louis Vuitton Neverfull MM Monogram", price: 21500, rating: 5.0, category: "Hand Bag", image: "/src/assets/products/p4441.jpg" },
{ id: "p4442", name: "Gucci Marmont Matelassé Shoulder Bag", price: 18500, rating: 4.9, category: "Hand Bag", image: "/src/assets/products/p4442.jpg" },
{ id: "p4443", name: "Prada Cleo Brushed Leather Shoulder Bag", price: 22999, rating: 4.9, category: "Hand Bag", image: "/src/assets/products/p4443.jpg" },
{ id: "p4444", name: "Dior Book Tote Large Blue Oblique", price: 25999, rating: 5.0, category: "Hand Bag", image: "/src/assets/products/p4444.jpg" },
{ id: "p4445", name: "Chanel Classic Flap Bag Lambskin", price: 28999, rating: 5.0, category: "Hand Bag", image: "/src/assets/products/p4445.jpg" },
{ id: "p4446", name: "Hermès Birkin 30 Togo Leather", price: 45000, rating: 5.0, category: "Hand Bag", image: "/src/assets/products/p4446.jpg" },
{ id: "p4447", name: "Balenciaga Hourglass XS Croc Embossed", price: 17999, rating: 4.8, category: "Hand Bag", image: "/src/assets/products/p4447.jpg" },
{ id: "p4448", name: "Versace La Medusa Mini Bag", price: 16999, rating: 4.8, category: "Hand Bag", image: "/src/assets/products/p4448.jpg" },
{ id: "p4449", name: "Fendi Peekaboo Iconic Medium Bag", price: 24999, rating: 4.9, category: "Hand Bag", image: "/src/assets/products/p4449.jpg" },
{ id: "p4450", name: "Marc Jacobs The Snapshot Camera Bag", price: 9200, rating: 4.7, category: "Hand Bag", image: "/src/assets/products/p4450.jpg" },
{ id: "p4451", name: "Coach Willis Top Handle 18", price: 8900, rating: 4.6, category: "Hand Bag", image: "/src/assets/products/p4451.jpg" },
{ id: "p4452", name: "Tory Burch Fleming Convertible Shoulder Bag", price: 9900, rating: 4.8, category: "Hand Bag", image: "/src/assets/products/p4452.jpg" },
{ id: "p4453", name: "Kate Spade Manhattan Quilted Tote", price: 9400, rating: 4.6, category: "Hand Bag", image: "/src/assets/products/p4453.jpg" },
{ id: "p4454", name: "Michael Kors Mercer Medium Pebbled Leather", price: 10200, rating: 4.7, category: "Hand Bag", image: "/src/assets/products/p4454.jpg" },
{ id: "p4455", name: "Guess Vikky Chain Tote", price: 6200, rating: 4.4, category: "Hand Bag", image: "/src/assets/products/p4455.jpg" },
{ id: "p4456", name: "Charles & Keith Croc-Embossed Shoulder Bag", price: 5400, rating: 4.5, category: "Hand Bag", image: "/src/assets/products/p4456.jpg" },
{ id: "p4457", name: "Baggit Zen Vegan Hobo", price: 4800, rating: 4.2, category: "Hand Bag", image: "/src/assets/products/p4457.jpg" },
{ id: "p4458", name: "Lavie Beech Dome Satchel", price: 4300, rating: 4.3, category: "Hand Bag", image: "/src/assets/products/p4458.jpg" },
{ id: "p4459", name: "Hidesign Crossbody Sling Bag", price: 6600, rating: 4.5, category: "Hand Bag", image: "/src/assets/products/p4459.jpg" },
{ id: "p4460", name: "Caprese Elina Structured Tote", price: 4700, rating: 4.2, category: "Hand Bag", image: "/src/assets/products/p4460.jpg" },
{ id: "p4461", name: "Bottega Veneta Cassette Padded Crossbody", price: 22500, rating: 4.9, category: "Hand Bag", image: "/src/assets/products/p4461.jpg" },
{ id: "p4462", name: "Celine Triomphe Canvas Shoulder Bag", price: 23999, rating: 5.0, category: "Hand Bag", image: "/src/assets/products/p4462.jpg" },
{ id: "p4463", name: "Mulberry Bayswater Leather Tote", price: 19500, rating: 4.9, category: "Hand Bag", image: "/src/assets/products/p4463.jpg" },
{ id: "p4464", name: "Ralph Lauren Dryden Marcy Satchel", price: 8900, rating: 4.6, category: "Hand Bag", image: "/src/assets/products/p4464.jpg" },
{ id: "p4465", name: "Anita Dongre Handcrafted Tote", price: 7200, rating: 4.5, category: "Hand Bag", image: "/src/assets/products/p4465.jpg" },
{ id: "p4466", name: "Allen Solly Formal Shoulder Bag", price: 5100, rating: 4.3, category: "Hand Bag", image: "/src/assets/products/p4466.jpg" },
{ id: "p4467", name: "Van Heusen City Leather Bag", price: 5900, rating: 4.4, category: "Hand Bag", image: "/src/assets/products/p4467.jpg" },
{ id: "p4468", name: "Da Milano Croco-Embossed Tote", price: 7900, rating: 4.5, category: "Hand Bag", image: "/src/assets/products/p4468.jpg" },
{ id: "p4469", name: "H&M Quilted Crossbody Bag", price: 2900, rating: 4.2, category: "Hand Bag", image: "/src/assets/products/p4469.jpg" },
{ id: "p4470", name: "ZARA Mini City Bag with Metal Handle", price: 3500, rating: 4.3, category: "Hand Bag", image: "/src/assets/products/p4470.jpg" },


{ id: "p51", name: "Nike Sportswear Heritage Backpack", price: 3500, rating: 4.5, category: "Backpacks", image: "/src/assets/products/p51.jpg" },
{ id: "p52", name: "Adidas Originals Classic Trefoil Backpack", price: 3200, rating: 4.4, category: "Backpacks", image: "/src/assets/products/p52.jpg" },
{ id: "p53", name: "Puma Phase Casual Backpack", price: 2800, rating: 4.3, category: "Backpacks", image: "/src/assets/products/p53.jpg" },
{ id: "p54", name: "Under Armour Hustle Pro Laptop Backpack", price: 4200, rating: 4.6, category: "Backpacks", image: "/src/assets/products/p54.jpg" },
{ id: "p55", name: "Wildcraft Bravo Laptop Backpack", price: 2700, rating: 4.4, category: "Backpacks", image: "/src/assets/products/p55.jpg" },
{ id: "p56", name: "Fastrack Reflex Travel Backpack", price: 3100, rating: 4.2, category: "Backpacks", image: "/src/assets/products/p56.jpg" },
{ id: "p57", name: "Tommy Hilfiger Classic Leather Backpack", price: 7200, rating: 4.7, category: "Backpacks", image: "/src/assets/products/p57.jpg" },
{ id: "p58", name: "Gucci GG Supreme Canvas Backpack", price: 14500, rating: 4.9, category: "Backpacks", image: "/src/assets/products/p58.jpg" },
{ id: "p59", name: "Louis Vuitton Christopher PM Monogram", price: 17500, rating: 5.0, category: "Backpacks", image: "/src/assets/products/p59.jpg" },
{ id: "p60", name: "Calvin Klein City Casual Backpack", price: 5800, rating: 4.5, category: "Backpacks", image: "/src/assets/products/p60.jpg" },
  { id: "p5551", name: "Armani Exchange Street Style Backpack", price: 6900, rating: 4.6, category: "Backpacks", image: "/src/assets/products/p5551.jpg" },
 { id: "p5552", name: "Prada Re-Nylon Travel Backpack", price: 18999, rating: 4.9, category: "Backpacks", image: "/src/assets/products/p5552.jpg" },
   
  { id: "p61", name: "Purse 1", price: 650, rating: 4.5, category: "Purse", image: "/src/assets/products/p61.jpg" },
  { id: "p62", name: "Purse 2", price: 800, rating: 4.6, category: "Purse", image: "/src/assets/products/p62.jpg" },
  { id: "p63", name: "Purse 3", price: 950, rating: 4.7, category: "Purse", image: "/src/assets/products/p63.jpg" },
  { id: "p64", name: "Purse 4", price: 1100, rating: 4.0, category: "Purse", image: "/src/assets/products/p64.jpg" },
  { id: "p65", name: "Purse 5", price: 1000, rating: 4.1, category: "Purse", image: "/src/assets/products/p65.jpg" },
  { id: "p66", name: "Purse 6", price: 1150, rating: 4.2, category: "Purse", image: "/src/assets/products/p66.jpg" },
  { id: "p67", name: "Purse 7", price: 1300, rating: 4.3, category: "Purse", image: "/src/assets/products/p67.jpg" },
  { id: "p68", name: "Purse 8", price: 1450, rating: 4.4, category: "Purse", image: "/src/assets/products/p68.jpg" },
  //{ id: "p69", name: "Purse 9", price: 1600, rating: 4.5, category: "Purse", image: "/src/assets/products/p69.jpg" },
  //{ id: "p70", name: "Purse 10", price: 1500, rating: 4.6, category: "Purse", image: "/src/assets/products/p70.jpg" },
// --- Jackets (p71 to p80) ---
{ id: "p71", name: "Nike Windrunner Heritage Jacket", price: 4800, rating: 4.5, category: "Jackets", image: "/src/assets/products/p71.jpg" },
{ id: "p72", name: "Adidas Originals Firebird Track Jacket", price: 4500, rating: 4.4, category: "Jackets", image: "/src/assets/products/p72.jpg" },
{ id: "p73", name: "Puma Iconic T7 Track Jacket", price: 4300, rating: 4.3, category: "Jackets", image: "/src/assets/products/p73.jpg" },
{ id: "p74", name: "Under Armour Storm Windbreaker", price: 5200, rating: 4.6, category: "Jackets", image: "/src/assets/products/p74.jpg" },
{ id: "p75", name: "The North Face Resolve Waterproof Jacket", price: 8900, rating: 4.8, category: "Jackets", image: "/src/assets/products/p75.jpg" },
{ id: "p76", name: "Columbia Flash Forward Down Jacket", price: 7600, rating: 4.7, category: "Jackets", image: "/src/assets/products/p76.jpg" },
{ id: "p77", name: "Decathlon Quechua SH100 Hooded Jacket", price: 3500, rating: 4.4, category: "Jackets", image: "/src/assets/products/p77.jpg" },
{ id: "p78", name: "H&M Bomber Jacket", price: 4100, rating: 4.3, category: "Jackets", image: "/src/assets/products/p78.jpg" },
{ id: "p79", name: "ZARA Faux Leather Moto Jacket", price: 5400, rating: 4.5, category: "Jackets", image: "/src/assets/products/p79.jpg" },
{ id: "p80", name: "Levi’s Trucker Denim Jacket", price: 6200, rating: 4.6, category: "Jackets", image: "/src/assets/products/p80.jpg" },
{ id: "p7781", name: "Diesel Hooded Denim Hybrid Jacket", price: 8800, rating: 4.6, category: "Jackets", image: "/src/assets/products/p7781.jpg" },
{ id: "p7782", name: "Off-White Arrow Print Coach Jacket", price: 29999, rating: 4.9, category: "Jackets", image: "/src/assets/products/p7782.jpg" },
{ id: "p7783", name: "Moncler Grenoble Down Jacket", price: 38999, rating: 5.0, category: "Jackets", image: "/src/assets/products/p7783.jpg" },
{ id: "p7784", name: "Stone Island Shadow Project Jacket", price: 31500, rating: 4.9, category: "Jackets", image: "/src/assets/products/p7784.jpg" },
{ id: "p7785", name: "Nike x Travis Scott Cactus Jack Bomber", price: 18999, rating: 4.8, category: "Jackets", image: "/src/assets/products/p7785.jpg" },
{ id: "p7786", name: "Adidas Originals Varsity Jacket", price: 8900, rating: 4.7, category: "Jackets", image: "/src/assets/products/p7786.jpg" },
{ id: "p7787", name: "Puma x Ferrari Racing Jacket", price: 9800, rating: 4.6, category: "Jackets", image: "/src/assets/products/p7787.jpg" },
{ id: "p7788", name: "Canada Goose Hybridge Lite Down Jacket", price: 45999, rating: 5.0, category: "Jackets", image: "/src/assets/products/p7788.jpg" },

// --- Pants (p81 to p90) ---
{ id: "p81", name: "Levi’s 511 Slim Fit Jeans", price: 4200, rating: 4.5, category: "Pants", image: "/src/assets/products/p81.jpg" },
{ id: "p82", name: "Wrangler Authentics Straight Fit Denim", price: 3900, rating: 4.4, category: "Pants", image: "/src/assets/products/p82.jpg" },
{ id: "p83", name: "Lee Cooper Comfort Stretch Jeans", price: 3700, rating: 4.3, category: "Pants", image: "/src/assets/products/p83.jpg" },
{ id: "p84", name: "Jack & Jones Skinny Fit Black Jeans", price: 4600, rating: 4.5, category: "Pants", image: "/src/assets/products/p84.jpg" },
{ id: "p85", name: "H&M Cargo Utility Pants", price: 3500, rating: 4.3, category: "Pants", image: "/src/assets/products/p85.jpg" },
{ id: "p86", name: "ZARA Slim Fit Chino Trousers", price: 4900, rating: 4.6, category: "Pants", image: "/src/assets/products/p86.jpg" },
{ id: "p87", name: "Calvin Klein Relaxed Fit Denim", price: 7200, rating: 4.7, category: "Pants", image: "/src/assets/products/p87.jpg" },
{ id: "p88", name: "Tommy Hilfiger Heritage Cotton Pants", price: 6900, rating: 4.7, category: "Pants", image: "/src/assets/products/p88.jpg" },
{ id: "p89", name: "Adidas Originals 3-Stripes Joggers", price: 4100, rating: 4.4, category: "Pants", image: "/src/assets/products/p89.jpg" },
{ id: "p90", name: "Nike Tech Fleece Jogger Pants", price: 5300, rating: 4.8, category: "Pants", image: "/src/assets/products/p90.jpg" },
{ id: "p8881", name: "Gucci GG Monogram Denim Jeans", price: 24999, rating: 4.9, category: "Pants", image: "/src/assets/products/p8881.jpg" },
{ id: "p8882", name: "Louis Vuitton Slim Fit Cotton Pants", price: 32999, rating: 5.0, category: "Pants", image: "/src/assets/products/p8882.jpg" },
{ id: "p8883", name: "Balmain Paris Moto Biker Jeans", price: 45999, rating: 5.0, category: "Pants", image: "/src/assets/products/p8883.jpg" },
{ id: "p8884", name: "Diesel D-Contrac Skinny Fit Jeans", price: 8900, rating: 4.7, category: "Pants", image: "/src/assets/products/p8884.jpg" },
{ id: "p8885", name: "Off-White Diagonal Stripe Sweatpants", price: 28999, rating: 4.9, category: "Pants", image: "/src/assets/products/p8885.jpg" },
{ id: "p8886", name: "Versace Baroque Print Track Pants", price: 25999, rating: 4.9, category: "Pants", image: "/src/assets/products/p8886.jpg" },
{ id: "p8887", name: "Fear of God Essentials Sweatpants", price: 17999, rating: 4.8, category: "Pants", image: "/src/assets/products/p8887.jpg" },
{ id: "p8888", name: "Amiri Distressed Skinny Jeans", price: 35999, rating: 5.0, category: "Pants", image: "/src/assets/products/p8888.jpg" },
{ id: "p8889", name: "Palm Angels Track Pants", price: 26999, rating: 4.9, category: "Pants", image: "/src/assets/products/p8889.jpg" },
{ id: "p8890", name: "Prada Re-Nylon Straight Fit Pants", price: 38999, rating: 5.0, category: "Pants", image: "/src/assets/products/p8890.jpg" },

  
{ id: "p91", name: "1 MILLION GREEN 100ML", price: 4999, rating: 4.4, category: "Perfume for Women", image: "/src/assets/products/p91.jpg" },
{ id: "p92", name: "BURBERRY LONDON EDP", price: 4999, rating: 4.3, category: "Perfume for Women", image: "/src/assets/products/p92.jpg" },
{ id: "p93", name: "BURBERRY WEEKEND EDP 100ml For Her", price: 4999, rating: 4.2, category: "Perfume for Women", image: "/src/assets/products/p93.jpg" },
{ id: "p94", name: "CAROLINA HERRERA GOOD GIRL NEW YORK", price: 4999, rating: 4.5, category: "Perfume for Women", image: "/src/assets/products/p94.jpg" },
{ id: "p95", name: "Carolina Herrera New York Dot Drama", price: 4999, rating: 4.4, category: "Perfume for Women", image: "/src/assets/products/p95.jpg" },
{ id: "p96", name: "Carolina Herrera Good Girl 80ML", price: 4999, rating: 4.3, category: "Perfume for Women", image: "/src/assets/products/p96.jpg" },
{ id: "p97", name: "CREED SPRING FLOWER EDP 100ml", price: 4999, rating: 4.6, category: "Perfume for Women", image: "/src/assets/products/p97.jpg" },
{ id: "p98", name: "DOLCE & GABBANA FRUIT COLLECTION", price: 4999, rating: 4.5, category: "Perfume for Women", image: "/src/assets/products/p98.jpg" },
{ id: "p99", name: "GIORGIO ARMANI SI INTENSE EDP 100ml", price: 4999, rating: 4.4, category: "Perfume for Women", image: "/src/assets/products/p99.jpg" },
{ id: "p100", name: "GUCCI FLORA GORGEOUS MAGNOLIA EDP", price: 4999, rating: 4.6, category: "Perfume for Women", image: "/src/assets/products/p100.jpg" },
{ id: "p101", name: "Gucci Bamboo Pink EDP 70ML", price: 4999, rating: 4.2, category: "Perfume for Women", image: "/src/assets/products/p101.jpg" },
{ id: "p102", name: "JEAN PAUL GAULTIER ELIXIR ABSOLU", price: 4999, rating: 4.4, category: "Perfume for Women", image: "/src/assets/products/p102.jpg" },
{ id: "p103", name: "Louis Vuitton Le Jour Se Leve 100ML", price: 4999, rating: 4.7, category: "Perfume for Women", image: "/src/assets/products/p103.jpg" },
{ id: "p104", name: "Paco Rabanne Fame Eau de Parfum", price: 4999, rating: 4.3, category: "Perfume for Women", image: "/src/assets/products/p104.jpg" },
{ id: "p105", name: "PORTRAITS PENHALICONS LORD GEORGE", price: 4999, rating: 4.5, category: "Perfume for Women", image: "/src/assets/products/p105.jpg" },
{ id: "p106", name: "PRADA MILANO PARADOXE EDP 90ML", price: 4999, rating: 4.4, category: "Perfume for Women", image: "/src/assets/products/p106.jpg" },
{ id: "p107", name: "Jean Paul Gaultier La Belle Fleur", price: 4999, rating: 4.6, category: "Perfume for Women", image: "/src/assets/products/p107.jpg" },
{ id: "p108", name: "Yves Saint Laurent Libre EDP", price: 4999, rating: 4.5, category: "Perfume for Women", image: "/src/assets/products/p108.jpg" },
{ id: "p109", name: "TOM FORD TOBACCO VANILLE EDP 100ML", price: 4999, rating: 4.7, category: "Perfume for Women", image: "/src/assets/products/p109.jpg" },
{ id: "p110", name: "Tom Ford Electric Cherry 100ML", price: 4999, rating: 4.6, category: "Perfume for Women", image: "/src/assets/products/p110.jpg" },
{ id: "p111", name: "Versace Yellow Diamond 90ML", price: 4999, rating: 4.5, category: "Perfume for Women", image: "/src/assets/products/p111.jpg" },
{ id: "p112", name: "VICTORIA’S SECRET DREAM ANGEL EDP 100ML", price: 4999, rating: 4.3, category: "Perfume for Women", image: "/src/assets/products/p112.jpg" },
{ id: "p113", name: "YSL MANIFESTO", price: 4999, rating: 4.4, category: "Perfume for Women", image: "/src/assets/products/p113.jpg" },
{ id: "p114", name: "PRADA MILANO PARADOXE EDP", price: 4499, rating: 4.8, category: "Perfume for Women", image: "/src/assets/products/p114.jpg" },

{ id: "p115", name: "212 VIP BLACK OWN THE PARTY NUC EDP", price: 4999, rating: 4.4, category: "Perfume for Men", image: "/src/assets/products/p115.jpg" },
{ id: "p116", name: "212 SEXY MEN EAU DE TOILETTE", price: 7000, rating: 4.5, category: "Perfume for Men", image: "/src/assets/products/p116.jpg" },
{ id: "p117", name: "AZZARO FOREVER WANTED GOLDEN EDP", price: 5200, rating: 4.3, category: "Perfume for Men", image: "/src/assets/products/p117.jpg" },
{ id: "p118", name: "Carolina Herrera Bad Boy New York 100ML", price: 5400, rating: 4.6, category: "Perfume for Men", image: "/src/assets/products/p118.jpg" },
{ id: "p119", name: "Diesel Only The Brave Black EDP 100ML", price: 4800, rating: 4.2, category: "Perfume for Men", image: "/src/assets/products/p119.jpg" },
{ id: "p120", name: "Diptyque L’Ombre Dans L’Eau EDP 75ML", price: 4999, rating: 4.5, category: "Perfume for Men", image: "/src/assets/products/p120.jpg" },
{ id: "p121", name: "Diptyque Philosykos EDP 75ML", price: 4900, rating: 4.3, category: "Perfume for Men", image: "/src/assets/products/p121.jpg" },
{ id: "p122", name: "Hugo Boss Bottled Elixir 100ML", price: 4999, rating: 4.6, category: "Perfume for Men", image: "/src/assets/products/p122.jpg" },
{ id: "p123", name: "Invictus Paco Rabanne", price: 4999, rating: 4.4, category: "Perfume for Men", image: "/src/assets/products/p123.jpg" },
{ id: "p124", name: "Jaguar Classic Chromite EDP 100ML", price: 4500, rating: 4.2, category: "Perfume for Men", image: "/src/assets/products/p124.jpg" },


  { id: "p125", name: "Men’s Watch 1", price: 650, rating: 4.1, category: "Men’s Watch", image: "/src/assets/products/p125.jpg" },
  { id: "p126", name: "Men’s Watch 2", price: 800, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p126.jpg" },
  { id: "p127", name: "Men’s Watch 3", price: 950, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p127.jpg" },
  { id: "p128", name: "Men’s Watch 4", price: 1100, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p128.jpg" },
  { id: "p129", name: "Men’s Watch 5", price: 1000, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p129.jpg" },
  { id: "p130", name: "Men’s Watch 6", price: 1150, rating: 4.6, category: "Men’s Watch", image: "/src/assets/products/p130.jpg" },
  { id: "p131", name: "Men’s Watch 7", price: 1300, rating: 4.7, category: "Men’s Watch", image: "/src/assets/products/p131.jpg" },
  { id: "p132", name: "Men’s Watch 8", price: 1450, rating: 4.0, category: "Men’s Watch", image: "/src/assets/products/p132.jpg" },
  { id: "p133", name: "Men’s Watch 9", price: 1600, rating: 4.1, category: "Men’s Watch", image: "/src/assets/products/p133.jpg" },
  { id: "p134", name: "Men’s Watch 10", price: 1500, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p134.jpg" },
  { id: "p135", name: "Men’s Watch 11", price: 1299, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p135.jpg" },
  { id: "p136", name: "Men’s Watch 12", price: 1300, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p136.jpg" },
  { id: "p137", name: "Men’s Watch 13", price: 1800, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p137.jpg" },
  { id: "p138", name: "Men’s Watch 14", price: 1699, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p138.jpg" },
  { id: "p139", name: "Men’s Watch 15", price: 1099, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p139.jpg" },
  { id: "p140", name: "Men’s Watch 16", price: 1199, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p140.jpg" },
  // { id: "p141", name: "Men’s Watch 17", price: 1500, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p137.jpg" },
  // { id: "p142", name: "Men’s Watch 18", price: 1700, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p138.jpg" },
  // { id: "p143", name: "Men’s Watch 19", price: 1299, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p139.jpg" },
  // { id: "p144", name: "Men’s Watch 20", price: 1100, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p140.jpg" },

  { id: "p141", name: "Versace", price: 5600, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p141.jpg" },
  { id: "p142", name: "Michael Kors 100 Series", price: 6899, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p142.jpg" },
  { id: "p143", name: "Calvin Klein", price: 5000, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p143.jpg" },
  { id: "p144", name: "Michael Kors Plam Japan", price: 7999, rating: 4.6, category: "Men’s Watch", image: "/src/assets/products/p144.jpg" },
  { id: "p145", name: "Michael Kors Wren Chronograph", price: 6000, rating: 4.1, category: "Men’s Watch", image: "/src/assets/products/p145.jpg" },
  { id: "p146", name: "Michael Kors Parker For Her AAA JAPAN", price: 7899, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p146.jpg" },
  { id: "p147", name: "Michael Kors Lexington 2Ton-Copper-Copper", price: 8999, rating: 4.7, category: "Men’s Watch", image: "/src/assets/products/p147.jpg" },
  { id: "p148", name: "Michael Kors Sofie", price: 5600, rating: 4.0, category: "Men’s Watch", image: "/src/assets/products/p148.jpg" },
  { id: "p149", name: "Fossi Tailor", price: 7899, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p149.jpg" },
  { id: "p150", name: "Armani", price: 5000, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p150.jpg" },

  { id: "p151", name: "Michael Kors Parker", price: 7000, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p151.jpg" },
  { id: "p152", name: "Richard Mille RM-07", price: 8999, rating: 4.7, category: "Men’s Watch", image: "/src/assets/products/p152.jpg" },
  { id: "p153", name: "Gucci 25H Womens Store Article Watch", price: 6899, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p153.jpg" },
  { id: "p154", name: "Michael Kors Plam Japan", price: 7999, rating: 4.6, category: "Men’s Watch", image: "/src/assets/products/p154.jpg" },
  { id: "p155", name: "Fossi I Tailor", price: 7999, rating: 4.1, category: "Men’s Watch", image: "/src/assets/products/p155.jpg" },
  { id: "p156", name: "Emporio Armani For Her", price: 5700, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p156.jpg" },
  { id: "p157", name: "Michael Kors Bradshaw", price: 4000, rating: 4.0, category: "Men’s Watch", image: "/src/assets/products/p157.jpg" },
  { id: "p158", name: "Michael Kors Parker For Her ΑΛΑ", price: 7899, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p158.jpg" },
  { id: "p159", name: "Portia Japan", price: 6899, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p159.jpg" },
  { id: "p160", name: "Michael Kors Plam Japan", price: 6899, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p160.jpg" },

  { id: "p161", name: "Rolex Celine", price: 5500, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p161.jpg" },
  { id: "p162", name: "Emporio Armani For Her", price: 5600, rating: 4.1, category: "Men’s Watch", image: "/src/assets/products/p162.jpg" },
  { id: "p163", name: "Emporio Armani AR1486 Ceramic For Her", price: 6700, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p163.jpg" },
  { id: "p164", name: "Rolex Celine", price: 7899, rating: 4.7, category: "Men’s Watch", image: "/src/assets/products/p164.jpg" },
  { id: "p165", name: "Michael Kors Lexington Gold-White", price: 9500, rating: 4.6, category: "Men’s Watch", image: "/src/assets/products/p165.jpg" },
  { id: "p166", name: "Emporio Armani AR11245 Japan Quality AAA Silver", price: 6000, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p166.jpg" },
  { id: "p167", name: "Fossil Ladies", price: 4500, rating: 4.0, category: "Men’s Watch", image: "/src/assets/products/p167.jpg" },
  { id: "p168", name: "Michael Kors Parker Japan AAA", price: 7999, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p168.jpg" },
  { id: "p169", name: "Michael Kors For Her AAA", price: 7999, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p169.jpg" },
  { id: "p170", name: "Portia Japan", price: 7999, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p170.jpg" },

  { id: "p171", name: "Michael Kors Ladies Watch", price: 5000, rating: 4.1, category: "Men’s Watch", image: "/src/assets/products/p171.jpg" },
  { id: "p172", name: "Michael Kors Ladies Watch Green Dial", price: 9500, rating: 4.6, category: "Men’s Watch", image: "/src/assets/products/p172.jpg" },
  { id: "p173", name: "Michael Kors For Her AAA", price: 8999, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p173.jpg" },
  { id: "p174", name: "G Shock GM 110G Watch", price: 5899, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p174.jpg" },
  { id: "p175", name: "Omega Seamaster Diver 300M Automatic", price: 9999, rating: 4.8, category: "Men’s Watch", image: "/src/assets/products/p175.jpg" },
  { id: "p176", name: "Jacob & Co. CR7 Blue Silicon Strap Premium Automatic Watch", price: 11999, rating: 4.7, category: "Men’s Watch", image: "/src/assets/products/p176.jpg" },
  { id: "p177", name: "Rolex Daytona", price: 15999, rating: 4.9, category: "Men’s Watch", image: "/src/assets/products/p177.jpg" },
  { id: "p178", name: "Tag Heuer Carrera", price: 12999, rating: 4.8, category: "Men’s Watch", image: "/src/assets/products/p178.jpg" },
  { id: "p179", name: "Patek Philippe Nautilus", price: 18999, rating: 5.0, category: "Men’s Watch", image: "/src/assets/products/p179.jpg" },
  { id: "p180", name: "Breitling Chronomat", price: 13999, rating: 4.6, category: "Men’s Watch", image: "/src/assets/products/p180.jpg" },

  { id: "p181", name: "Rolex Submariner", price: 22999, rating: 4.9, category: "Men’s Watch", image: "/src/assets/products/p181.jpg" },
  { id: "p182", name: "Hublot Big Bang", price: 16999, rating: 4.8, category: "Men’s Watch", image: "/src/assets/products/p182.jpg" },
  { id: "p183", name: "Cartier Santos", price: 14999, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p183.jpg" },
  { id: "p184", name: "Panerai Luminor", price: 15999, rating: 4.7, category: "Men’s Watch", image: "/src/assets/products/p184.jpg" },
  { id: "p185", name: "IWC Portugieser", price: 17999, rating: 4.8, category: "Men’s Watch", image: "/src/assets/products/p185.jpg" },
  { id: "p186", name: "Zenith Defy", price: 14990, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p186.jpg" },
  { id: "p187", name: "Seiko Presage", price: 8999, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p187.jpg" },
  { id: "p188", name: "Tissot PRX", price: 7999, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p188.jpg" },
  { id: "p189", name: "Longines HydroConquest", price: 9999, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p189.jpg" },
  { id: "p190", name: "Rado Centrix", price: 8999, rating: 4.6, category: "Men’s Watch", image: "/src/assets/products/p190.jpg" },
  { id: "p191", name: "Tommy Hilfiger Automatic Watch", price: 6300, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p191.jpg" },
  { id: "p192", name: "Fossi Townsman Chain Belt", price: 5899, rating: 4.1, category: "Men’s Watch", image: "/src/assets/products/p192.jpg" },
  { id: "p193", name: "Michael Kors Lexington Premium", price: 6800, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p193.jpg" },
  { id: "p194", name: "Rolex Just Date Automatic Watch", price: 6800, rating: 4.6, category: "Men’s Watch", image: "/src/assets/products/p194.jpg" },
  { id: "p195", name: "S Watch Neon Jelly White Chronograph Official Premium", price: 6200, rating: 4.0, category: "Men’s Watch", image: "/src/assets/products/p195.jpg" },
  { id: "p196", name: "G-Shock GM 2100 All Working", price: 4000, rating: 4.1, category: "Men’s Watch", image: "/src/assets/products/p196.jpg" },
  { id: "p197", name: "Patek Philippe Nautilus Silver Black", price: 6800, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p197.jpg" },
  { id: "p198", name: "Citizen Tsuyosa Open Heart Premium Automatic", price: 6800, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p198.jpg" },
  { id: "p199", name: "Tissot 1853 Chemin Chronograph", price: 4999, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p199.jpg" },
  { id: "p200", name: "Diesel 13 Bar Big Daddy 2Ton-Copper-Black", price: 7000, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p200.jpg" },

  { id: "p201", name: "Armani Exchange Chronograph", price: 5800, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p201.jpg" },
  { id: "p202", name: "Casio Edifice ECB-2000", price: 7000, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p202.jpg" },
  { id: "p203", name: "Emporio Armani Meccanico Automatic", price: 5999, rating: 4.1, category: "Men’s Watch", image: "/src/assets/products/p203.jpg" },
  { id: "p204", name: "Cartier Ballon Automatic", price: 6000, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p204.jpg" },
  { id: "p205", name: "Tissot PRC 200 Chronograph", price: 5600, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p205.jpg" },
  { id: "p206", name: "Versace Aion Chronograph", price: 4800, rating: 4.0, category: "Men’s Watch", image: "/src/assets/products/p206.jpg" },
  { id: "p207", name: "Michael Kors Bradshaw Chronograph", price: 7200, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p207.jpg" },
  { id: "p208", name: "Rolex Oyster Perpetual", price: 15500, rating: 4.8, category: "Men’s Watch", image: "/src/assets/products/p208.jpg" },
  { id: "p209", name: "Tissot Seastar 1000 Powermatic", price: 9800, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p209.jpg" },
  { id: "p210", name: "Fossil Nate Chronograph", price: 6500, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p210.jpg" },
  { id: "p211", name: "Omega Constellation Automatic", price: 18500, rating: 4.7, category: "Men’s Watch", image: "/src/assets/products/p211.jpg" },
  { id: "p212", name: "Tag Heuer Formula 1", price: 12500, rating: 4.6, category: "Men’s Watch", image: "/src/assets/products/p212.jpg" },
  { id: "p213", name: "Rado Captain Cook", price: 14999, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p213.jpg" },
  { id: "p214", name: "Seiko Presage Cocktail Time", price: 8200, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p214.jpg" },
  { id: "p215", name: "Casio G-Shock Mudmaster", price: 7200, rating: 4.1, category: "Men’s Watch", image: "/src/assets/products/p215.jpg" },
  { id: "p216", name: "Emporio Armani Classic Black Dial", price: 5800, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p216.jpg" },

  { id: "p217", name: "Longines Conquest V.H.P.", price: 11800, rating: 4.6, category: "Men’s Watch", image: "/src/assets/products/p217.jpg" },
  { id: "p218", name: "Gucci Dive Black Dial", price: 13200, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p218.jpg" },
  { id: "p219", name: "Versace V-Chrono", price: 10999, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p219.jpg" },
  { id: "p220", name: "Hugo Boss Chronograph Silver", price: 8700, rating: 4.1, category: "Men’s Watch", image: "/src/assets/products/p220.jpg" },
  { id: "p221", name: "Citizen Eco-Drive Titanium", price: 9500, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p221.jpg" },
  { id: "p222", name: "Hamilton Jazzmaster Open Heart", price: 13999, rating: 4.7, category: "Men’s Watch", image: "/src/assets/products/p222.jpg" },
  { id: "p223", name: "Michael Kors Dylan Chronograph", price: 7200, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p223.jpg" },
  { id: "p224", name: "Fossil Townsman Automatic", price: 6400, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p224.jpg" },

  // { id: "p229", name: "Michael Kors Ladies Watch", price: 5000, rating: 4.1, category: "Women’s Watch", image: "/src/assets/products/p229.jpg" },
  // { id: "p230", name: "Michael Kors For Her AAA", price: 7999, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p230.jpg" },
  // { id: "p231", name: "Michael Kors For Her AAA Premium", price: 8999, rating: 4.5, category: "Women’s Watch", image: "/src/assets/products/p231.jpg" },
  // { id: "p232", name: "Michael Kors Bradshaw", price: 4000, rating: 4.0, category: "Women’s Watch", image: "/src/assets/products/p232.jpg" },
  // { id: "p233", name: "Michael Kors 100 Series", price: 6899, rating: 4.3, category: "Women’s Watch", image: "/src/assets/products/p233.jpg" },
  // { id: "p234", name: "Michael Kors Ladies Watch Green Dial", price: 9500, rating: 4.6, category: "Women’s Watch", image: "/src/assets/products/p234.jpg" },
  // { id: "p235", name: "Gucci 25H Women’s Store Article Watch", price: 6899, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p235.jpg" },
  // { id: "p236", name: "Fossil Ladies", price: 4500, rating: 4.1, category: "Women’s Watch", image: "/src/assets/products/p236.jpg" },
  // { id: "p237", name: "Fossi I Tailor", price: 7899, rating: 4.2, category: "Women’s Watch", image: "/src/assets/products/p237.jpg" },
  // { id: "p238", name: "Fossi I Tailor Premium", price: 7999, rating: 4.3, category: "Women’s Watch", image: "/src/assets/products/p238.jpg" },
  // { id: "p239", name: "Emporio Armani For Her", price: 5600, rating: 4.2, category: "Women’s Watch", image: "/src/assets/products/p239.jpg" },
  // { id: "p240", name: "Emporio Armani AR11245 Japan Quality AAA", price: 7499, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p240.jpg" },
  // { id: "p241", name: "Emporio Armani AR1486 Ceramic For Her", price: 6700, rating: 4.3, category: "Women’s Watch", image: "/src/assets/products/p241.jpg" },
  // { id: "p242", name: "Calvin Klein", price: 5000, rating: 4.1, category: "Women’s Watch", image: "/src/assets/products/p242.jpg" },
  // { id: "p243", name: "Armani Classic", price: 5000, rating: 4.0, category: "Women’s Watch", image: "/src/assets/products/p243.jpg" },
  // { id: "p244", name: "Michael Kors Elegant Edition", price: 7200, rating: 4.3, category: "Women’s Watch", image: "/src/assets/products/p244.jpg" },

  // { id: "p245", name: "Rolex Lady-Datejust", price: 18999, rating: 4.8, category: "Women’s Watch", image: "/src/assets/products/p245.jpg" },
  // { id: "p246", name: "Tissot Flamingo", price: 10999, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p246.jpg" },
  // { id: "p247", name: "Michael Kors Parker Chronograph", price: 8200, rating: 4.3, category: "Women’s Watch", image: "/src/assets/products/p247.jpg" },
  // { id: "p248", name: "Gucci G-Timeless Women’s Edition", price: 12999, rating: 4.6, category: "Women’s Watch", image: "/src/assets/products/p248.jpg" },
  // { id: "p249", name: "Rado Florence Classic", price: 13999, rating: 4.5, category: "Women’s Watch", image: "/src/assets/products/p249.jpg" },
  // { id: "p250", name: "Cartier Panthère de Cartier", price: 22999, rating: 4.9, category: "Women’s Watch", image: "/src/assets/products/p250.jpg" },
  // { id: "p251", name: "Omega De Ville Ladymatic", price: 19999, rating: 4.7, category: "Women’s Watch", image: "/src/assets/products/p251.jpg" },
  // { id: "p252", name: "Versace Medusa Icon", price: 9999, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p252.jpg" },
  // { id: "p253", name: "Michael Kors Sofie Pavé", price: 8799, rating: 4.2, category: "Women’s Watch", image: "/src/assets/products/p253.jpg" },
  // { id: "p254", name: "Fossil Jacqueline Leather", price: 6500, rating: 4.1, category: "Women’s Watch", image: "/src/assets/products/p254.jpg" },
  // { id: "p255", name: "Seiko Lukia Automatic", price: 9800, rating: 4.5, category: "Women’s Watch", image: "/src/assets/products/p255.jpg" },
  // { id: "p256", name: "Longines DolceVita", price: 14999, rating: 4.7, category: "Women’s Watch", image: "/src/assets/products/p256.jpg" },
  // { id: "p257", name: "Citizen Eco-Drive Silhouette", price: 7200, rating: 4.2, category: "Women’s Watch", image: "/src/assets/products/p257.jpg" },
  // { id: "p258", name: "Hublot Spirit of Big Bang Women", price: 22999, rating: 4.9, category: "Women’s Watch", image: "/src/assets/products/p258.jpg" },
  // { id: "p259", name: "Emporio Armani Ceramica Women", price: 7700, rating: 4.3, category: "Women’s Watch", image: "/src/assets/products/p259.jpg" },
  // { id: "p260", name: "Michael Kors Mini Slim Runway", price: 6900, rating: 4.1, category: "Women’s Watch", image: "/src/assets/products/p260.jpg" },
  // { id: "p261", name: "Gucci 25H Diamond Edition", price: 19999, rating: 4.8, category: "Women’s Watch", image: "/src/assets/products/p261.jpg" },
  // { id: "p262", name: "Tissot Lovely Square", price: 8200, rating: 4.2, category: "Women’s Watch", image: "/src/assets/products/p262.jpg" },
  // { id: "p263", name: "Rolex Pearlmaster", price: 25999, rating: 5.0, category: "Women’s Watch", image: "/src/assets/products/p263.jpg" },
  // { id: "p264", name: "Michael Kors Camille Chronograph", price: 7800, rating: 4.2, category: "Women’s Watch", image: "/src/assets/products/p264.jpg" },
  // { id: "p265", name: "Rado Centrix Diamonds", price: 15999, rating: 4.6, category: "Women’s Watch", image: "/src/assets/products/p265.jpg" },
  // { id: "p266", name: "Versace Palazzo Empire Women’s", price: 11800, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p266.jpg" },
  // { id: "p267", name: "Fossil Scarlette Mini", price: 6400, rating: 4.1, category: "Women’s Watch", image: "/src/assets/products/p267.jpg" },
  // { id: "p268", name: "Cartier Ballon Bleu Women", price: 21999, rating: 4.9, category: "Women’s Watch", image: "/src/assets/products/p268.jpg" },
 

{ id: "p271", name: "Michael Kors Parker Rose Gold Watch", price: 8999, rating: 4.8, category: "Women’s Watch", image: "/src/assets/products/p271.jpg" },
{ id: "p272", name: "Fossil Jacqueline Multifunction Leather Watch", price: 7499, rating: 4.7, category: "Women’s Watch", image: "/src/assets/products/p272.jpg" },
{ id: "p273", name: "Daniel Wellington Petite Melrose", price: 8999, rating: 4.8, category: "Women’s Watch", image: "/src/assets/products/p273.jpg" },
{ id: "p274", name: "Titan Raga Viva Gold Dial Watch", price: 5499, rating: 4.5, category: "Women’s Watch", image: "/src/assets/products/p274.jpg" },
{ id: "p275", name: "Casio Sheen Analog Mother of Pearl Dial", price: 6200, rating: 4.6, category: "Women’s Watch", image: "/src/assets/products/p275.jpg" },
{ id: "p276", name: "Guess Nova Crystal Embellished Watch", price: 9700, rating: 4.8, category: "Women’s Watch", image: "/src/assets/products/p276.jpg" },
{ id: "p277", name: "Anne Klein Rose Gold Bracelet Watch", price: 7200, rating: 4.6, category: "Women’s Watch", image: "/src/assets/products/p277.jpg" },
{ id: "p278", name: "Tommy Hilfiger Silver Dial Chain Watch", price: 8900, rating: 4.7, category: "Women’s Watch", image: "/src/assets/products/p278.jpg" },
{ id: "p279", name: "Olivia Burton Wonderland Blush Dial", price: 7800, rating: 4.7, category: "Women’s Watch", image: "/src/assets/products/p279.jpg" },
{ id: "p280", name: "Armani Exchange Lady Hampton Watch", price: 9500, rating: 4.8, category: "Women’s Watch", image: "/src/assets/products/p280.jpg" },
{ id: "p281", name: "Michael Kors Sofie Pavé Smartwatch", price: 14999, rating: 4.9, category: "Women’s Watch", image: "/src/assets/products/p281.jpg" },
{ id: "p282", name: "Fossil Carlie Mini Two-Tone Bracelet Watch", price: 6999, rating: 4.7, category: "Women’s Watch", image: "/src/assets/products/p282.jpg" },
{ id: "p283", name: "Citizen Eco-Drive Rose Gold Watch", price: 9999, rating: 4.8, category: "Women’s Watch", image: "/src/assets/products/p283.jpg" },
{ id: "p284", name: "Emporio Armani Gianni T-Bar Watch", price: 13499, rating: 4.9, category: "Women’s Watch", image: "/src/assets/products/p284.jpg" },
{ id: "p285", name: "Casio Enticer Blue Leather Strap Watch", price: 5400, rating: 4.5, category: "Women’s Watch", image: "/src/assets/products/p285.jpg" },
{ id: "p286", name: "Titan Raga Espana Blue Dial Watch", price: 8600, rating: 4.6, category: "Women’s Watch", image: "/src/assets/products/p286.jpg" },
{ id: "p287", name: "Versace Greca Logo Two-Tone Watch", price: 28999, rating: 5.0, category: "Women’s Watch", image: "/src/assets/products/p287.jpg" },
{ id: "p288", name: "Gucci G-Timeless Bee Dial Watch", price: 27999, rating: 5.0, category: "Women’s Watch", image: "/src/assets/products/p288.jpg" },
{ id: "p289", name: "Chanel Premiere Mini Gold Link Watch", price: 31999, rating: 5.0, category: "Women’s Watch", image: "/src/assets/products/p289.jpg" },
{ id: "p290", name: "Dior La Mini D My Dior", price: 34999, rating: 5.0, category: "Women’s Watch", image: "/src/assets/products/p290.jpg" },
{ id: "p291", name: "Louis Vuitton Tambour Slim Monogram", price: 45999, rating: 5.0, category: "Women’s Watch", image: "/src/assets/products/p291.jpg" },
{ id: "p292", name: "Hermès Heure H Mini Watch", price: 49999, rating: 5.0, category: "Women’s Watch", image: "/src/assets/products/p292.jpg" },
{ id: "p293", name: "Balmain Elegance Chic Gold Watch", price: 15999, rating: 4.9, category: "Women’s Watch", image: "/src/assets/products/p293.jpg" },
{ id: "p294", name: "Longines DolceVita Silver Strap", price: 23999, rating: 4.9, category: "Women’s Watch", image: "/src/assets/products/p294.jpg" },
{ id: "p295", name: "Tissot Flamingo Stainless Steel Watch", price: 18999, rating: 4.8, category: "Women’s Watch", image: "/src/assets/products/p295.jpg" },
{ id: "p296", name: "Coach Park Stainless Steel Bracelet Watch", price: 11999, rating: 4.7, category: "Women’s Watch", image: "/src/assets/products/p296.jpg" },
{ id: "p297", name: "Michael Kors Lexington Gold-Tone Watch", price: 10499, rating: 4.8, category: "Women’s Watch", image: "/src/assets/products/p297.jpg" },
{ id: "p298", name: "Cartier Panthère de Cartier Watch", price: 47999, rating: 5.0, category: "Women’s Watch", image: "/src/assets/products/p298.jpg" },
{ id: "p299", name: "Bvlgari Serpenti Tubogas Pink Gold", price: 54999, rating: 5.0, category: "Women’s Watch", image: "/src/assets/products/p299.jpg" },
{ id: "p300", name: "Rolex Lady Datejust Gold Jubilee", price: 58999, rating: 5.0, category: "Women’s Watch", image: "/src/assets/products/p300.jpg" },


{ id: "p301", name: "Ray-Ban Aviator Classic RB3025", price: 7200, rating: 4.8, category: "Men’s Sunglasses", image: "/src/assets/products/p301.jpg" },
{ id: "p302", name: "Oakley Holbrook Matte Black Prizm", price: 8500, rating: 4.7, category: "Men’s Sunglasses", image: "/src/assets/products/p302.jpg" },
{ id: "p303", name: "Police SPL872 Polarized Sunglasses", price: 6900, rating: 4.6, category: "Men’s Sunglasses", image: "/src/assets/products/p303.jpg" },
{ id: "p304", name: "Carrera Champion Pilot Shades", price: 6300, rating: 4.5, category: "Men’s Sunglasses", image: "/src/assets/products/p304.jpg" },
{ id: "p305", name: "Persol PO0714 Folding Sunglasses", price: 9800, rating: 4.9, category: "Men’s Sunglasses", image: "/src/assets/products/p305.jpg" },
{ id: "p306", name: "Tommy Hilfiger Rectangular Black Frame", price: 6400, rating: 4.5, category: "Men’s Sunglasses", image: "/src/assets/products/p306.jpg" },
{ id: "p307", name: "Fastrack Polarized Square Sunglasses", price: 3100, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p307.jpg" },
{ id: "p308", name: "Calvin Klein UV400 Metal Frame Shades", price: 7200, rating: 4.7, category: "Men’s Sunglasses", image: "/src/assets/products/p308.jpg" },
{ id: "p309", name: "Prada Linea Rossa PS05TS Sunglasses", price: 12999, rating: 4.9, category: "Men’s Sunglasses", image: "/src/assets/products/p309.jpg" },
{ id: "p310", name: "Armani Exchange AX4105S", price: 7500, rating: 4.7, category: "Men’s Sunglasses", image: "/src/assets/products/p310.jpg" },
{ id: "p311", name: "Ray-Ban Wayfarer RB2140", price: 8400, rating: 4.8, category: "Men’s Sunglasses", image: "/src/assets/products/p311.jpg" },
{ id: "p312", name: "Gucci GG0061S Oversized Square Frame", price: 18999, rating: 5.0, category: "Men’s Sunglasses", image: "/src/assets/products/p312.jpg" },
{ id: "p313", name: "Versace Medusa Biggie Sunglasses", price: 16999, rating: 4.9, category: "Men’s Sunglasses", image: "/src/assets/products/p313.jpg" },
{ id: "p314", name: "Bvlgari BV7034 Polarized", price: 15500, rating: 4.9, category: "Men’s Sunglasses", image: "/src/assets/products/p314.jpg" },
{ id: "p315", name: "Montblanc Meisterstück Pilot Shades", price: 14500, rating: 4.8, category: "Men’s Sunglasses", image: "/src/assets/products/p315.jpg" },
{ id: "p316", name: "Louis Vuitton LV Satellite Sunglasses", price: 25999, rating: 5.0, category: "Men’s Sunglasses", image: "/src/assets/products/p316.jpg" },
{ id: "p317", name: "Dior Homme BlackTie 249", price: 22999, rating: 5.0, category: "Men’s Sunglasses", image: "/src/assets/products/p317.jpg" },
{ id: "p318", name: "Tom Ford FT0237 Snowdon", price: 16999, rating: 4.9, category: "Men’s Sunglasses", image: "/src/assets/products/p318.jpg" },
{ id: "p319", name: "Balmain Aviator Gold Frame", price: 23999, rating: 5.0, category: "Men’s Sunglasses", image: "/src/assets/products/p319.jpg" },
{ id: "p320", name: "Cartier Santos-Dumont Sunglasses", price: 29999, rating: 5.0, category: "Men’s Sunglasses", image: "/src/assets/products/p320.jpg" },
{ id: "p321", name: "Porsche Design P8478 Interchangeable Lens", price: 18500, rating: 4.9, category: "Men’s Sunglasses", image: "/src/assets/products/p321.jpg" },
{ id: "p322", name: "Emporio Armani EA4175", price: 7700, rating: 4.6, category: "Men’s Sunglasses", image: "/src/assets/products/p322.jpg" },
{ id: "p323", name: "Ray-Ban Clubmaster RB3016", price: 7900, rating: 4.8, category: "Men’s Sunglasses", image: "/src/assets/products/p323.jpg" },
{ id: "p324", name: "Hugo Boss Pilot Metal Sunglasses", price: 9900, rating: 4.7, category: "Men’s Sunglasses", image: "/src/assets/products/p324.jpg" },
{ id: "p325", name: "Police Titanium Frame Pilot Shades", price: 8800, rating: 4.7, category: "Men’s Sunglasses", image: "/src/assets/products/p325.jpg" },
{ id: "p326", name: "Burberry BE3108 Round Sunglasses", price: 12900, rating: 4.8, category: "Men’s Sunglasses", image: "/src/assets/products/p326.jpg" },
{ id: "p327", name: "Persol Steve McQueen Special Edition", price: 16999, rating: 4.9, category: "Men’s Sunglasses", image: "/src/assets/products/p327.jpg" },
{ id: "p328", name: "Tommy Hilfiger Pilot Blue Mirror Shades", price: 6700, rating: 4.5, category: "Men’s Sunglasses", image: "/src/assets/products/p328.jpg" },
{ id: "p329", name: "Boss Orange Polarized Square Frame", price: 8100, rating: 4.7, category: "Men’s Sunglasses", image: "/src/assets/products/p329.jpg" },
{ id: "p330", name: "Carrera Ducati Shield Sunglasses", price: 8700, rating: 4.8, category: "Men’s Sunglasses", image: "/src/assets/products/p330.jpg" },
{ id: "p331", name: "Fendi Black Round Sunglasses", price: 14200, rating: 4.9, category: "Men’s Sunglasses", image: "/src/assets/products/p331.jpg" },
{ id: "p332", name: "Oakley Sutro Road Cycling Shades", price: 9500, rating: 4.8, category: "Men’s Sunglasses", image: "/src/assets/products/p332.jpg" },
{ id: "p333", name: "Gucci GG0208S Square Metal Frame", price: 16999, rating: 4.9, category: "Men’s Sunglasses", image: "/src/assets/products/p333.jpg" },
{ id: "p334", name: "Versace VE4391 Medusa Pilot", price: 18999, rating: 5.0, category: "Men’s Sunglasses", image: "/src/assets/products/p334.jpg" },
{ id: "p335", name: "Cartier Panthère De Cartier Sunglasses", price: 31999, rating: 5.0, category: "Men’s Sunglasses", image: "/src/assets/products/p335.jpg" },
{ id: "p336", name: "Prada Sport PS53NS Aviator Shades", price: 13999, rating: 4.9, category: "Men’s Sunglasses", image: "/src/assets/products/p336.jpg" },
{ id: "p337", name: "Dolce & Gabbana DG2233", price: 14500, rating: 4.9, category: "Men’s Sunglasses", image: "/src/assets/products/p337.jpg" },
{ id: "p338", name: "Givenchy GV7082 Pilot Sunglasses", price: 15999, rating: 4.9, category: "Men’s Sunglasses", image: "/src/assets/products/p338.jpg" },
{ id: "p339", name: "Ray-Ban Justin RB4165", price: 6900, rating: 4.7, category: "Men’s Sunglasses", image: "/src/assets/products/p339.jpg" },
{ id: "p340", name: "Tom Ford Henry FT0248", price: 16999, rating: 4.9, category: "Men’s Sunglasses", image: "/src/assets/products/p340.jpg" },
{ id: "p341", name: "Chanel 4189C Metal Frame Sunglasses", price: 27999, rating: 5.0, category: "Men’s Sunglasses", image: "/src/assets/products/p341.jpg" },
{ id: "p342", name: "BOSS by Hugo Boss Aviator Gradient", price: 9700, rating: 4.7, category: "Men’s Sunglasses", image: "/src/assets/products/p342.jpg" },
{ id: "p343", name: "Oakley Radar EV Path", price: 11500, rating: 4.8, category: "Men’s Sunglasses", image: "/src/assets/products/p343.jpg" },
{ id: "p344", name: "Police VPL559 Polarized Frame", price: 8800, rating: 4.6, category: "Men’s Sunglasses", image: "/src/assets/products/p344.jpg" },
{ id: "p345", name: "Emporio Armani EA4189", price: 7700, rating: 4.6, category: "Men’s Sunglasses", image: "/src/assets/products/p345.jpg" },
{ id: "p346", name: "Ray-Ban RB3548N Hexagonal Flat Lens", price: 9100, rating: 4.8, category: "Men’s Sunglasses", image: "/src/assets/products/p346.jpg" },
{ id: "p347", name: "Porsche Design P8649 Black Gold", price: 18999, rating: 4.9, category: "Men’s Sunglasses", image: "/src/assets/products/p347.jpg" },
{ id: "p348", name: "Dolce & Gabbana DG4354 Havana Frame", price: 15999, rating: 4.9, category: "Men’s Sunglasses", image: "/src/assets/products/p348.jpg" },
{ id: "p349", name: "Louis Vuitton Square Pilot Gold Frame", price: 29999, rating: 5.0, category: "Men’s Sunglasses", image: "/src/assets/products/p349.jpg" },
{ id: "p350", name: "Cartier CT0250S Full Rim Gold", price: 32999, rating: 5.0, category: "Men’s Sunglasses", image: "/src/assets/products/p350.jpg" },
{ id: "p351", name: "Ray-Ban New Caravan RB3136", price: 7400, rating: 4.7, category: "Men’s Sunglasses", image: "/src/assets/products/p351.jpg" },
{ id: "p352", name: "Tom Ford Ace FT0611", price: 17999, rating: 4.9, category: "Men’s Sunglasses", image: "/src/assets/products/p352.jpg" },
{ id: "p353", name: "Dior Homme Blacktie 256", price: 24999, rating: 5.0, category: "Men’s Sunglasses", image: "/src/assets/products/p353.jpg" },
{ id: "p354", name: "Gucci GG1157S Geometric Frame", price: 18999, rating: 5.0, category: "Men’s Sunglasses", image: "/src/assets/products/p354.jpg" },
{ id: "p355", name: "Burberry BE4334F Square Sunglasses", price: 14500, rating: 4.9, category: "Men’s Sunglasses", image: "/src/assets/products/p355.jpg" },
{ id: "p356", name: "Versace VE4393 Barocco Print", price: 17999, rating: 4.9, category: "Men’s Sunglasses", image: "/src/assets/products/p356.jpg" },
{ id: "p357", name: "Bvlgari BV8226 Metal Bridge", price: 15999, rating: 4.8, category: "Men’s Sunglasses", image: "/src/assets/products/p357.jpg" },
{ id: "p358", name: "Tommy Hilfiger Polarized Square", price: 6500, rating: 4.5, category: "Men’s Sunglasses", image: "/src/assets/products/p358.jpg" },
{ id: "p359", name: "Police SPL872 Gradient Blue", price: 7100, rating: 4.6, category: "Men’s Sunglasses", image: "/src/assets/products/p359.jpg" },
{ id: "p360", name: "Ray-Ban Round Metal RB3447", price: 8200, rating: 4.8, category: "Men’s Sunglasses", image: "/src/assets/products/p360.jpg" },


{ id: "p371", name: "Michael Kors Chelsea Aviator Sunglasses", price: 8500, rating: 4.8, category: "Ladies Sunglasses", image: "/src/assets/products/p371.jpg" },
{ id: "p372", name: "Fossil Cate Cat Eye Sunglasses", price: 7200, rating: 4.6, category: "Ladies Sunglasses", image: "/src/assets/products/p372.jpg" },
{ id: "p373", name: "Coach HC7093 L1149B Sunglasses", price: 9500, rating: 4.7, category: "Ladies Sunglasses", image: "/src/assets/products/p373.jpg" },
{ id: "p374", name: "Kate Spade Annora Square Frame", price: 6800, rating: 4.6, category: "Ladies Sunglasses", image: "/src/assets/products/p374.jpg" },
{ id: "p375", name: "Vogue Eyewear Cat Eye Gradient", price: 5900, rating: 4.5, category: "Ladies Sunglasses", image: "/src/assets/products/p375.jpg" },
{ id: "p376", name: "Ray-Ban Erika RB4171", price: 8800, rating: 4.8, category: "Ladies Sunglasses", image: "/src/assets/products/p376.jpg" },
{ id: "p377", name: "Tommy Hilfiger Oversized Gradient Frame", price: 6400, rating: 4.5, category: "Ladies Sunglasses", image: "/src/assets/products/p377.jpg" },
{ id: "p378", name: "Calvin Klein CK19111 Cat Eye Shades", price: 7500, rating: 4.6, category: "Ladies Sunglasses", image: "/src/assets/products/p378.jpg" },
{ id: "p379", name: "Emporio Armani EA4137 Oval Sunglasses", price: 8800, rating: 4.7, category: "Ladies Sunglasses", image: "/src/assets/products/p379.jpg" },
{ id: "p380", name: "Gucci GG0036S Oversized Sunglasses", price: 18999, rating: 5.0, category: "Ladies Sunglasses", image: "/src/assets/products/p380.jpg" },
{ id: "p381", name: "Versace VE4361 Butterfly Sunglasses", price: 17999, rating: 4.9, category: "Ladies Sunglasses", image: "/src/assets/products/p381.jpg" },
{ id: "p382", name: "Dior So Real Pop Sunglasses", price: 22999, rating: 5.0, category: "Ladies Sunglasses", image: "/src/assets/products/p382.jpg" },
{ id: "p383", name: "Prada PR01VS Minimal Baroque Frame", price: 20999, rating: 4.9, category: "Ladies Sunglasses", image: "/src/assets/products/p383.jpg" },
{ id: "p384", name: "Louis Vuitton My Fair Lady Sunglasses", price: 25999, rating: 5.0, category: "Ladies Sunglasses", image: "/src/assets/products/p384.jpg" },
{ id: "p385", name: "Chanel Butterfly Polarized Sunglasses", price: 28999, rating: 5.0, category: "Ladies Sunglasses", image: "/src/assets/products/p385.jpg" },
{ id: "p386", name: "Bvlgari Serpenti Cat Eye Sunglasses", price: 26999, rating: 4.9, category: "Ladies Sunglasses", image: "/src/assets/products/p386.jpg" },
{ id: "p387", name: "Fendi F is Fendi Oversized Round Shades", price: 19999, rating: 4.9, category: "Ladies Sunglasses", image: "/src/assets/products/p387.jpg" },
{ id: "p388", name: "Jimmy Choo Spark Crystal Sunglasses", price: 14999, rating: 4.8, category: "Ladies Sunglasses", image: "/src/assets/products/p388.jpg" },
{ id: "p389", name: "Burberry BE4308 Round Havana Sunglasses", price: 13499, rating: 4.8, category: "Ladies Sunglasses", image: "/src/assets/products/p389.jpg" },
{ id: "p390", name: "Coach L1148 Gold Mirror Shades", price: 9500, rating: 4.7, category: "Ladies Sunglasses", image: "/src/assets/products/p390.jpg" },
{ id: "p391", name: "Vogue VO4132SB Gradient Cat Eye", price: 6400, rating: 4.5, category: "Ladies Sunglasses", image: "/src/assets/products/p391.jpg" },
{ id: "p392", name: "Ray-Ban RB3547 Oval Metal Sunglasses", price: 9100, rating: 4.8, category: "Ladies Sunglasses", image: "/src/assets/products/p392.jpg" },
{ id: "p393", name: "Marc Jacobs MJ 106S Square Frame", price: 9800, rating: 4.8, category: "Ladies Sunglasses", image: "/src/assets/products/p393.jpg" },
{ id: "p394", name: "Guess GU7695 Crystal Cat Eye", price: 7200, rating: 4.6, category: "Ladies Sunglasses", image: "/src/assets/products/p394.jpg" },
{ id: "p395", name: "Kate Spade Aria Round Gradient Shades", price: 6500, rating: 4.6, category: "Ladies Sunglasses", image: "/src/assets/products/p395.jpg" },
{ id: "p396", name: "Tory Burch TY7140U Square Sunglasses", price: 10499, rating: 4.8, category: "Ladies Sunglasses", image: "/src/assets/products/p396.jpg" },
{ id: "p397", name: "Dolce & Gabbana DG4348 Embellished Frame", price: 15999, rating: 4.9, category: "Ladies Sunglasses", image: "/src/assets/products/p397.jpg" },
{ id: "p398", name: "Cartier Panthère de Cartier Gold Frame", price: 30999, rating: 5.0, category: "Ladies Sunglasses", image: "/src/assets/products/p398.jpg" },

{ id: "p401", name: "Ray-Ban RX7047 Transparent Blue Frame", price: 7500, rating: 4.8, category: "Frames", image: "/src/assets/products/p401.jpg" },
{ id: "p402", name: "Oakley OX8156 Pitchman R Polished Black", price: 9800, rating: 4.9, category: "Frames", image: "/src/assets/products/p402.jpg" },
{ id: "p403", name: "Gucci GG0397O Tortoise Gold Frame", price: 18999, rating: 5.0, category: "Frames", image: "/src/assets/products/p403.jpg" },
{ id: "p404", name: "Prada VPR 16MZ Cat Eye Optical Frame", price: 20999, rating: 4.9, category: "Frames", image: "/src/assets/products/p404.jpg" },
{ id: "p405", name: "Versace VE3218B Crystal Studded Frame", price: 17999, rating: 4.8, category: "Frames", image: "/src/assets/products/p405.jpg" },
{ id: "p406", name: "Emporio Armani EA1119 Round Metal Frame", price: 8999, rating: 4.7, category: "Frames", image: "/src/assets/products/p406.jpg" },
{ id: "p407", name: "Michael Kors MK3032 Bleecker Square Frame", price: 8500, rating: 4.6, category: "Frames", image: "/src/assets/products/p407.jpg" },
{ id: "p408", name: "Tommy Hilfiger TH 1718 Optical Frame", price: 7200, rating: 4.6, category: "Frames", image: "/src/assets/products/p408.jpg" },
{ id: "p409", name: "Fossil FOS 7077 Round Vintage Frame", price: 6900, rating: 4.5, category: "Frames", image: "/src/assets/products/p409.jpg" },
{ id: "p410", name: "Calvin Klein CK18102 Semi-Rimless Frame", price: 8800, rating: 4.7, category: "Frames", image: "/src/assets/products/p410.jpg" },
{ id: "p411", name: "Burberry BE2323 Square Optical Frame", price: 13999, rating: 4.9, category: "Frames", image: "/src/assets/products/p411.jpg" },
{ id: "p412", name: "Cartier CT0232O Panthère Rimless Gold Frame", price: 30999, rating: 5.0, category: "Frames", image: "/src/assets/products/p412.jpg" },
{ id: "p413", name: "Dior BlackTie 256 Optical Acetate Frame", price: 28999, rating: 5.0, category: "Frames", image: "/src/assets/products/p413.jpg" },
{ id: "p414", name: "Bvlgari BV1115K Full Rim Premium Frame", price: 26999, rating: 4.9, category: "Frames", image: "/src/assets/products/p414.jpg" },

];

export default MOCK_PRODUCTS;
