const MOCK_PRODUCTS = [
// Women's Kick Section
{ id: "p1", name: "Adidas 700 V3 Azael For Her", originalPrice: 12400, price: 7750, rating: 4.7, category: "Women’s Kick", image: "/src/assets/products/p1.jpg" },
{ id: "p2", name: "Air Jordan 1 Mid Magenta", originalPrice: 11800, price: 7350, rating: 4.8, category: "Women’s Kick", image: "/src/assets/products/p2.jpg" },
{ id: "p3", name: "Nike Air Max 2090 Pink Edition", originalPrice: 10600, price: 6650, rating: 4.6, category: "Women’s Kick", image: "/src/assets/products/p3.jpg" },
{ id: "p4", name: "Nike Air Force 1 Low Shadow", originalPrice: 12000, price: 7499, rating: 4.7, category: "Women’s Kick", image: "/src/assets/products/p4.jpg" },
{ id: "p5", name: "Dior x Air Jordan 1 High Premium", originalPrice: 14000, price: 8750, rating: 4.9, category: "Women’s Kick", image: "/src/assets/products/p5.jpg" },
{ id: "p6", name: "New Balance 327 Multi Color", originalPrice: 10500, price: 6500, rating: 4.5, category: "Women’s Kick", image: "/src/assets/products/p6.jpg" },
{ id: "p7", name: "Puma Cali Dream Luxe", originalPrice: 8800, price: 5500, rating: 4.4, category: "Women’s Kick", image: "/src/assets/products/p7.jpg" },
{ id: "p8", name: "Reebok Club C 85 Vintage White", originalPrice: 9700, price: 6050, rating: 4.6, category: "Women’s Kick", image: "/src/assets/products/p8.jpg" },
{ id: "p9", name: "Vans Old Skool Floral Edition", originalPrice: 9100, price: 5699, rating: 4.5, category: "Women’s Kick", image: "/src/assets/products/p9.jpg" },
{ id: "p10", name: "Converse Run Star Hike High Top", originalPrice: 12500, price: 7800, rating: 4.8, category: "Women’s Kick", image: "/src/assets/products/p10.jpg" },

// Men's Kick Section
{ id: "p11", name: "Nike Air Jordan 4 Retro Bred", originalPrice: 14000, price: 8750, rating: 4.8, category: "Men’s Kick", image: "/src/assets/products/p11.jpg" },
{ id: "p12", name: "Adidas Yeezy Boost 350 V2 Zebra", originalPrice: 15800, price: 9850, rating: 4.9, category: "Men’s Kick", image: "/src/assets/products/p12.jpg" },
{ id: "p13", name: "Nike Dunk Low Panda Edition", originalPrice: 11500, price: 7200, rating: 4.7, category: "Men’s Kick", image: "/src/assets/products/p13.jpg" },
{ id: "p14", name: "Puma RS-X Reinvention", originalPrice: 9800, price: 6100, rating: 4.5, category: "Men’s Kick", image: "/src/assets/products/p14.jpg" },
{ id: "p15", name: "Air Jordan 1 Retro High OG", originalPrice: 16200, price: 10100, rating: 4.9, category: "Men’s Kick", image: "/src/assets/products/p15.jpg" },
{ id: "p16", name: "Nike Air Max Plus OG", originalPrice: 13400, price: 8400, rating: 4.6, category: "Men’s Kick", image: "/src/assets/products/p16.jpg" },
{ id: "p17", name: "Reebok Zig Kinetica Edge 2.5", originalPrice: 9900, price: 6200, rating: 4.5, category: "Men’s Kick", image: "/src/assets/products/p17.jpg" },
{ id: "p18", name: "New Balance 550 White Green", originalPrice: 11800, price: 7350, rating: 4.7, category: "Men’s Kick", image: "/src/assets/products/p18.jpg" },
{ id: "p19", name: "Converse Chuck 70 High Black", originalPrice: 8700, price: 5400, rating: 4.4, category: "Men’s Kick", image: "/src/assets/products/p19.jpg" },
{ id: "p20", name: "Under Armour HOVR Phantom 2", originalPrice: 12600, price: 7900, rating: 4.6, category: "Men’s Kick", image: "/src/assets/products/p20.jpg" },

  // Wallets Section
{ id: "p21", name: "Dior Premium Quality Wallet 02", originalPrice: 4798, price: 2999, rating: 4.4, category: "Wallet", image: "/src/assets/products/p21.jpg" },
{ id: "p22", name: "Coach Printed Premium Quality Wallet 14", originalPrice: 5598, price: 3499, rating: 4.5, category: "Wallet", image: "/src/assets/products/p22.jpg" },
{ id: "p23", name: "Louis Vuitton Premium Quality Wallet 132", originalPrice: 5598, price: 3499, rating: 4.3, category: "Wallet", image: "/src/assets/products/p23.jpg" },
{ id: "p24", name: "Armani AX Wallet V781", originalPrice: 4798, price: 2999, rating: 4.4, category: "Wallet", image: "/src/assets/products/p24.jpg" },
{ id: "p25", name: "Burberry 34 Men’s Wallet With Original Box & Card", originalPrice: 5598, price: 3499, rating: 4.5, category: "Wallet", image: "/src/assets/products/p25.jpg" },
{ id: "p26", name: "Dior Wallet V720", originalPrice: 5278, price: 3299, rating: 4.3, category: "Wallet", image: "/src/assets/products/p26.jpg" },
{ id: "p27", name: "Gucci Long Wallet V418", originalPrice: 6400, price: 4000, rating: 4.6, category: "Wallet", image: "/src/assets/products/p27.jpg" },
{ id: "p28", name: "Gucci Wallet V743", originalPrice: 4798, price: 2999, rating: 4.2, category: "Wallet", image: "/src/assets/products/p28.jpg" },
{ id: "p29", name: "Gucci Wallet V754", originalPrice: 4798, price: 2999, rating: 4.4, category: "Wallet", image: "/src/assets/products/p29.jpg" },
{ id: "p30", name: "Gucci Wallet V755", originalPrice: 4798, price: 2999, rating: 4.3, category: "Wallet", image: "/src/assets/products/p30.jpg" },

// Additional Wallets
{ id: "p2221", name: "Supreme Louis Vuitton Wallet V596", originalPrice: 5278, price: 3299, rating: 4.5, category: "Wallet", image: "/src/assets/products/p2221.jpg" },
{ id: "p2222", name: "Louis Vuitton Wallet V714", originalPrice: 5278, price: 3299, rating: 4.4, category: "Wallet", image: "/src/assets/products/p2222.jpg" },
{ id: "p2223", name: "Louis Vuitton Wallet V752", originalPrice: 4798, price: 2999, rating: 4.3, category: "Wallet", image: "/src/assets/products/p2223.jpg" },
{ id: "p2224", name: "Louis Vuitton Wallet V779", originalPrice: 4798, price: 2999, rating: 4.4, category: "Wallet", image: "/src/assets/products/p2224.jpg" },
{ id: "p2225", name: "Michael Kors Long Wallet V733", originalPrice: 5278, price: 3299, rating: 4.5, category: "Wallet", image: "/src/assets/products/p2225.jpg" },
{ id: "p2226", name: "Michael Kors Long Wallet V735", originalPrice: 5278, price: 3299, rating: 4.4, category: "Wallet", image: "/src/assets/products/p2226.jpg" },

  {
    "id": "p31",
    "name": "Gucci GG Supreme Leather Belt",
    "originalPrice": 8500,
    "price": 1700,
    "rating": 4.8,
    "category": "Belt",
    "image": "/src/assets/products/p31.jpg"
  },
  {
    "id": "p32",
    "name": "Louis Vuitton Initiales Monogram Belt",
    "originalPrice": 9500,
    "price": 1900,
    "rating": 4.9,
    "category": "Belt",
    "image": "/src/assets/products/p32.jpg"
  },
  {
    "id": "p33",
    "name": "Herm\u00e8s H Buckle Leather Belt",
    "originalPrice": 12000,
    "price": 2400,
    "rating": 5.0,
    "category": "Belt",
    "image": "/src/assets/products/p33.jpg"
  },
  {
    "id": "p34",
    "name": "Armani Exchange Black Leather Belt",
    "originalPrice": 4200,
    "price": 850,
    "rating": 4.5,
    "category": "Belt",
    "image": "/src/assets/products/p34.jpg"
  },
  {
    "id": "p35",
    "name": "Calvin Klein Reversible Buckle Belt",
    "originalPrice": 3800,
    "price": 750,
    "rating": 4.4,
    "category": "Belt",
    "image": "/src/assets/products/p35.jpg"
  },
  {
    "id": "p36",
    "name": "Tommy Hilfiger Casual Brown Belt",
    "originalPrice": 3200,
    "price": 650,
    "rating": 4.3,
    "category": "Belt",
    "image": "/src/assets/products/p36.jpg"
  },
  {
    "id": "p37",
    "name": "Diesel Logo Engraved Leather Belt",
    "originalPrice": 4000,
    "price": 800,
    "rating": 4.6,
    "category": "Belt",
    "image": "/src/assets/products/p37.jpg"
  },
  {
    "id": "p38",
    "name": "Versace Medusa Buckle Belt",
    "originalPrice": 11000,
    "price": 2200,
    "rating": 4.9,
    "category": "Belt",
    "image": "/src/assets/products/p38.jpg"
  },
  {
    "id": "p39",
    "name": "BOSS Hugo Reversible Leather Belt",
    "originalPrice": 5000,
    "price": 1000,
    "rating": 4.5,
    "category": "Belt",
    "image": "/src/assets/products/p39.jpg"
  },
  {
    "id": "p40",
    "name": "Fossil Classic Black Leather Belt",
    "originalPrice": 2800,
    "price": 550,
    "rating": 4.2,
    "category": "Belt",
    "image": "/src/assets/products/p40.jpg"
  },
  {
    "id": "p3331",
    "name": "Montblanc Sartorial Leather Belt",
    "originalPrice": 9700,
    "price": 1950,
    "rating": 4.8,
    "category": "Belt",
    "image": "/src/assets/products/p3331.jpg"
  },
  {
    "id": "p3332",
    "name": "WildHorn Genuine Leather Belt",
    "originalPrice": 1900,
    "price": 400,
    "rating": 4.1,
    "category": "Belt",
    "image": "/src/assets/products/p3332.jpg"
  },
  {
    "id": "p3333",
    "name": "Allen Solly Formal Brown Belt",
    "originalPrice": 2500,
    "price": 500,
    "rating": 4.2,
    "category": "Belt",
    "image": "/src/assets/products/p3333.jpg"
  },
  {
    "id": "p3334",
    "name": "Woodland Outdoor Rugged Belt",
    "originalPrice": 2200,
    "price": 450,
    "rating": 4.3,
    "category": "Belt",
    "image": "/src/assets/products/p3334.jpg"
  },
  {
    "id": "p3335",
    "name": "Prada Saffiano Leather Belt",
    "originalPrice": 11500,
    "price": 2300,
    "rating": 5.0,
    "category": "Belt",
    "image": "/src/assets/products/p3335.jpg"
  },
  {
    "id": "p3336",
    "name": "Coach Signature Buckle Belt",
    "originalPrice": 6200,
    "price": 1250,
    "rating": 4.6,
    "category": "Belt",
    "image": "/src/assets/products/p3336.jpg"
  },
  {
    "id": "p3337",
    "name": "Salvatore Ferragamo Gancini Belt",
    "originalPrice": 9800,
    "price": 1950,
    "rating": 4.9,
    "category": "Belt",
    "image": "/src/assets/products/p3337.jpg"
  },
  {
    "id": "p3338",
    "name": "Burberry London Leather Check Belt",
    "originalPrice": 8900,
    "price": 1800,
    "rating": 4.8,
    "category": "Belt",
    "image": "/src/assets/products/p3338.jpg"
  },
  {
    "id": "p41",
    "name": "Michael Kors Jet Set Leather Tote",
    "originalPrice": 9500,
    "price": 1900,
    "rating": 4.8,
    "category": "Hand Bag",
    "image": "/src/assets/products/p41.jpg"
  },
  {
    "id": "p42",
    "name": "Coach Tabby Shoulder Bag 26",
    "originalPrice": 10500,
    "price": 2100,
    "rating": 4.7,
    "category": "Hand Bag",
    "image": "/src/assets/products/p42.png"
  },
  {
    "id": "p43",
    "name": "Tory Burch Perry Triple-Compartment Tote",
    "originalPrice": 11200,
    "price": 2250,
    "rating": 4.8,
    "category": "Hand Bag",
    "image": "/src/assets/products/p43.jpg"
  },
  {
    "id": "p44",
    "name": "Kate Spade Margaux Medium Satchel",
    "originalPrice": 8800,
    "price": 1750,
    "rating": 4.6,
    "category": "Hand Bag",
    "image": "/src/assets/products/p44.jpg"
  },
  {
    "id": "p45",
    "name": "Guess Alby Crossbody Flap",
    "originalPrice": 5600,
    "price": 1100,
    "rating": 4.5,
    "category": "Hand Bag",
    "image": "/src/assets/products/p45.jpg"
  },
  {
    "id": "p46",
    "name": "Charles & Keith Quilted Top Handle Bag",
    "originalPrice": 6300,
    "price": 1250,
    "rating": 4.5,
    "category": "Hand Bag",
    "image": "/src/assets/products/p46.jpg"
  },
  {
    "id": "p47",
    "name": "Fossil Fiona Leather Satchel",
    "originalPrice": 7200,
    "price": 1450,
    "rating": 4.6,
    "category": "Hand Bag",
    "image": "/src/assets/products/p47.jpg"
  },
  {
    "id": "p48",
    "name": "ALDO Barland Structured Handbag",
    "originalPrice": 4800,
    "price": 950,
    "rating": 4.3,
    "category": "Hand Bag",
    "image": "/src/assets/products/p48.jpg"
  },
  {
    "id": "p49",
    "name": "Calvin Klein Monogram Crossbody",
    "originalPrice": 5900,
    "price": 1200,
    "rating": 4.4,
    "category": "Hand Bag",
    "image": "/src/assets/products/p49.jpg"
  },
  {
    "id": "p50",
    "name": "Baggit Earthy Tan Vegan Tote",
    "originalPrice": 4600,
    "price": 900,
    "rating": 4.2,
    "category": "Hand Bag",
    "image": "/src/assets/products/p50.jpg"
  },
  {
    "id": "p4441",
    "name": "Louis Vuitton Neverfull MM Monogram",
    "originalPrice": 21500,
    "price": 4300,
    "rating": 5.0,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4441.jpg"
  },
  {
    "id": "p4442",
    "name": "Gucci Marmont Matelass\u00e9 Shoulder Bag",
    "originalPrice": 18500,
    "price": 3700,
    "rating": 4.9,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4442.jpg"
  },
  {
    "id": "p4443",
    "name": "Prada Cleo Brushed Leather Shoulder Bag",
    "originalPrice": 22999,
    "price": 4600,
    "rating": 4.9,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4443.jpg"
  },
  {
    "id": "p4444",
    "name": "Dior Book Tote Large Blue Oblique",
    "originalPrice": 25999,
    "price": 5200,
    "rating": 5.0,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4444.jpg"
  },
  {
    "id": "p4445",
    "name": "Chanel Classic Flap Bag Lambskin",
    "originalPrice": 28999,
    "price": 5800,
    "rating": 5.0,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4445.jpg"
  },
  {
    "id": "p4446",
    "name": "Herm\u00e8s Birkin 30 Togo Leather",
    "originalPrice": 45000,
    "price": 9000,
    "rating": 5.0,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4446.jpg"
  },
  {
    "id": "p4447",
    "name": "Balenciaga Hourglass XS Croc Embossed",
    "originalPrice": 17999,
    "price": 3600,
    "rating": 4.8,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4447.jpg"
  },
  {
    "id": "p4448",
    "name": "Versace La Medusa Mini Bag",
    "originalPrice": 16999,
    "price": 3400,
    "rating": 4.8,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4448.jpg"
  },
  {
    "id": "p4449",
    "name": "Fendi Peekaboo Iconic Medium Bag",
    "originalPrice": 24999,
    "price": 5000,
    "rating": 4.9,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4449.jpg"
  },
  {
    "id": "p4450",
    "name": "Marc Jacobs The Snapshot Camera Bag",
    "originalPrice": 9200,
    "price": 1850,
    "rating": 4.7,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4450.jpg"
  },
  {
    "id": "p4451",
    "name": "Coach Willis Top Handle 18",
    "originalPrice": 8900,
    "price": 1800,
    "rating": 4.6,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4451.jpg"
  },
  {
    "id": "p4452",
    "name": "Tory Burch Fleming Convertible Shoulder Bag",
    "originalPrice": 9900,
    "price": 2000,
    "rating": 4.8,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4452.jpg"
  },
  {
    "id": "p4453",
    "name": "Kate Spade Manhattan Quilted Tote",
    "originalPrice": 9400,
    "price": 1900,
    "rating": 4.6,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4453.jpg"
  },
  {
    "id": "p4454",
    "name": "Michael Kors Mercer Medium Pebbled Leather",
    "originalPrice": 10200,
    "price": 2050,
    "rating": 4.7,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4454.jpg"
  },
  {
    "id": "p4455",
    "name": "Guess Vikky Chain Tote",
    "originalPrice": 6200,
    "price": 1250,
    "rating": 4.4,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4455.jpg"
  },
  {
    "id": "p4456",
    "name": "Charles & Keith Croc-Embossed Shoulder Bag",
    "originalPrice": 5400,
    "price": 1100,
    "rating": 4.5,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4456.jpg"
  },
  {
    "id": "p4457",
    "name": "Baggit Zen Vegan Hobo",
    "originalPrice": 4800,
    "price": 950,
    "rating": 4.2,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4457.jpg"
  },
  {
    "id": "p4458",
    "name": "Lavie Beech Dome Satchel",
    "originalPrice": 4300,
    "price": 850,
    "rating": 4.3,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4458.jpg"
  },
  {
    "id": "p4459",
    "name": "Hidesign Crossbody Sling Bag",
    "originalPrice": 6600,
    "price": 1300,
    "rating": 4.5,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4459.jpg"
  },
  {
    "id": "p4460",
    "name": "Caprese Elina Structured Tote",
    "originalPrice": 4700,
    "price": 950,
    "rating": 4.2,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4460.jpg"
  },
  {
    "id": "p4461",
    "name": "Bottega Veneta Cassette Padded Crossbody",
    "originalPrice": 22500,
    "price": 4500,
    "rating": 4.9,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4461.jpg"
  },
  {
    "id": "p4462",
    "name": "Celine Triomphe Canvas Shoulder Bag",
    "originalPrice": 23999,
    "price": 4800,
    "rating": 5.0,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4462.jpg"
  },
  {
    "id": "p4463",
    "name": "Mulberry Bayswater Leather Tote",
    "originalPrice": 19500,
    "price": 3900,
    "rating": 4.9,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4463.jpg"
  },
  {
    "id": "p4464",
    "name": "Ralph Lauren Dryden Marcy Satchel",
    "originalPrice": 8900,
    "price": 1800,
    "rating": 4.6,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4464.jpg"
  },
  {
    "id": "p4465",
    "name": "Anita Dongre Handcrafted Tote",
    "originalPrice": 7200,
    "price": 1450,
    "rating": 4.5,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4465.jpg"
  },
  {
    "id": "p4466",
    "name": "Allen Solly Formal Shoulder Bag",
    "originalPrice": 5100,
    "price": 1000,
    "rating": 4.3,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4466.jpg"
  },
  {
    "id": "p4467",
    "name": "Van Heusen City Leather Bag",
    "originalPrice": 5900,
    "price": 1200,
    "rating": 4.4,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4467.jpg"
  },
  {
    "id": "p4468",
    "name": "Da Milano Croco-Embossed Tote",
    "originalPrice": 7900,
    "price": 1600,
    "rating": 4.5,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4468.jpg"
  },
  {
    "id": "p4469",
    "name": "H&M Quilted Crossbody Bag",
    "originalPrice": 2900,
    "price": 600,
    "rating": 4.2,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4469.jpg"
  },
  {
    "id": "p4470",
    "name": "ZARA Mini City Bag with Metal Handle",
    "originalPrice": 3500,
    "price": 700,
    "rating": 4.3,
    "category": "Hand Bag",
    "image": "/src/assets/products/p4470.jpg"
  },
  {
    "id": "p51",
    "name": "Nike Sportswear Heritage Backpack",
    "originalPrice": 3500,
    "price": 700,
    "rating": 4.5,
    "category": "Backpacks",
    "image": "/src/assets/products/p51.jpg"
  },
  {
    "id": "p52",
    "name": "Adidas Originals Classic Trefoil Backpack",
    "originalPrice": 3200,
    "price": 650,
    "rating": 4.4,
    "category": "Backpacks",
    "image": "/src/assets/products/p52.jpg"
  },
  {
    "id": "p53",
    "name": "Puma Phase Casual Backpack",
    "originalPrice": 2800,
    "price": 550,
    "rating": 4.3,
    "category": "Backpacks",
    "image": "/src/assets/products/p53.jpg"
  },
  {
    "id": "p54",
    "name": "Under Armour Hustle Pro Laptop Backpack",
    "originalPrice": 4200,
    "price": 850,
    "rating": 4.6,
    "category": "Backpacks",
    "image": "/src/assets/products/p54.jpg"
  },
  {
    "id": "p55",
    "name": "Wildcraft Bravo Laptop Backpack",
    "originalPrice": 2700,
    "price": 550,
    "rating": 4.4,
    "category": "Backpacks",
    "image": "/src/assets/products/p55.jpg"
  },
  {
    "id": "p56",
    "name": "Fastrack Reflex Travel Backpack",
    "originalPrice": 3100,
    "price": 600,
    "rating": 4.2,
    "category": "Backpacks",
    "image": "/src/assets/products/p56.jpg"
  },
  {
    "id": "p57",
    "name": "Tommy Hilfiger Classic Leather Backpack",
    "originalPrice": 7200,
    "price": 1450,
    "rating": 4.7,
    "category": "Backpacks",
    "image": "/src/assets/products/p57.jpg"
  },
  {
    "id": "p58",
    "name": "Gucci GG Supreme Canvas Backpack",
    "originalPrice": 14500,
    "price": 2900,
    "rating": 4.9,
    "category": "Backpacks",
    "image": "/src/assets/products/p58.jpg"
  },
  {
    "id": "p59",
    "name": "Louis Vuitton Christopher PM Monogram",
    "originalPrice": 17500,
    "price": 3500,
    "rating": 5.0,
    "category": "Backpacks",
    "image": "/src/assets/products/p59.jpg"
  },
  {
    "id": "p60",
    "name": "Calvin Klein City Casual Backpack",
    "originalPrice": 5800,
    "price": 1150,
    "rating": 4.5,
    "category": "Backpacks",
    "image": "/src/assets/products/p60.jpg"
  },
  {
    "id": "p5551",
    "name": "Armani Exchange Street Style Backpack",
    "originalPrice": 6900,
    "price": 1400,
    "rating": 4.6,
    "category": "Backpacks",
    "image": "/src/assets/products/p5551.jpg"
  },
  {
    "id": "p5552",
    "name": "Prada Re-Nylon Travel Backpack",
    "originalPrice": 18999,
    "price": 3800,
    "rating": 4.9,
    "category": "Backpacks",
    "image": "/src/assets/products/p5552.jpg"
  },
  {
    "id": "p61",
    "name": "Purse 1",
    "originalPrice": 650,
    "price": 150,
    "rating": 4.5,
    "category": "Purse",
    "image": "/src/assets/products/p61.jpg"
  },
  {
    "id": "p62",
    "name": "Purse 2",
    "originalPrice": 800,
    "price": 150,
    "rating": 4.6,
    "category": "Purse",
    "image": "/src/assets/products/p62.jpg"
  },
  {
    "id": "p63",
    "name": "Purse 3",
    "originalPrice": 950,
    "price": 200,
    "rating": 4.7,
    "category": "Purse",
    "image": "/src/assets/products/p63.jpg"
  },
  {
    "id": "p64",
    "name": "Purse 4",
    "originalPrice": 1100,
    "price": 200,
    "rating": 4.0,
    "category": "Purse",
    "image": "/src/assets/products/p64.jpg"
  },
  {
    "id": "p65",
    "name": "Purse 5",
    "originalPrice": 1000,
    "price": 200,
    "rating": 4.1,
    "category": "Purse",
    "image": "/src/assets/products/p65.jpg"
  },
  {
    "id": "p66",
    "name": "Purse 6",
    "originalPrice": 1150,
    "price": 250,
    "rating": 4.2,
    "category": "Purse",
    "image": "/src/assets/products/p66.jpg"
  },
  {
    "id": "p67",
    "name": "Purse 7",
    "originalPrice": 1300,
    "price": 250,
    "rating": 4.3,
    "category": "Purse",
    "image": "/src/assets/products/p67.jpg"
  },
  {
    "id": "p68",
    "name": "Purse 8",
    "originalPrice": 1450,
    "price": 300,
    "rating": 4.4,
    "category": "Purse",
    "image": "/src/assets/products/p68.jpg"
  },
  {
    "id": "p69",
    "name": "Purse 9",
    "originalPrice": 1600,
    "price": 300,
    "rating": 4.5,
    "category": "Purse",
    "image": "/src/assets/products/p69.jpg"
  },
  {
    "id": "p70",
    "name": "Purse 10",
    "originalPrice": 1500,
    "price": 300,
    "rating": 4.6,
    "category": "Purse",
    "image": "/src/assets/products/p70.jpg"
  },
  {
    "id": "p71",
    "name": "Nike Windrunner Heritage Jacket",
    "originalPrice": 4800,
    "price": 950,
    "rating": 4.5,
    "category": "Jackets",
    "image": "/src/assets/products/p71.jpg"
  },
  {
    "id": "p72",
    "name": "Adidas Originals Firebird Track Jacket",
    "originalPrice": 4500,
    "price": 900,
    "rating": 4.4,
    "category": "Jackets",
    "image": "/src/assets/products/p72.jpg"
  },
  {
    "id": "p73",
    "name": "Puma Iconic T7 Track Jacket",
    "originalPrice": 4300,
    "price": 850,
    "rating": 4.3,
    "category": "Jackets",
    "image": "/src/assets/products/p73.jpg"
  },
  {
    "id": "p74",
    "name": "Under Armour Storm Windbreaker",
    "originalPrice": 5200,
    "price": 1050,
    "rating": 4.6,
    "category": "Jackets",
    "image": "/src/assets/products/p74.jpg"
  },
  {
    "id": "p75",
    "name": "The North Face Resolve Waterproof Jacket",
    "originalPrice": 8900,
    "price": 1800,
    "rating": 4.8,
    "category": "Jackets",
    "image": "/src/assets/products/p75.jpg"
  },
  {
    "id": "p76",
    "name": "Columbia Flash Forward Down Jacket",
    "originalPrice": 7600,
    "price": 1500,
    "rating": 4.7,
    "category": "Jackets",
    "image": "/src/assets/products/p76.jpg"
  },
  {
    "id": "p77",
    "name": "Decathlon Quechua SH100 Hooded Jacket",
    "originalPrice": 3500,
    "price": 700,
    "rating": 4.4,
    "category": "Jackets",
    "image": "/src/assets/products/p77.jpg"
  },
  {
    "id": "p78",
    "name": "H&M Bomber Jacket",
    "originalPrice": 4100,
    "price": 800,
    "rating": 4.3,
    "category": "Jackets",
    "image": "/src/assets/products/p78.jpg"
  },
  {
    "id": "p79",
    "name": "ZARA Faux Leather Moto Jacket",
    "originalPrice": 5400,
    "price": 1100,
    "rating": 4.5,
    "category": "Jackets",
    "image": "/src/assets/products/p79.jpg"
  },
  {
    "id": "p80",
    "name": "Levi\u2019s Trucker Denim Jacket",
    "originalPrice": 6200,
    "price": 1250,
    "rating": 4.6,
    "category": "Jackets",
    "image": "/src/assets/products/p80.jpg"
  },
  {
    "id": "p7781",
    "name": "Diesel Hooded Denim Hybrid Jacket",
    "originalPrice": 8800,
    "price": 1750,
    "rating": 4.6,
    "category": "Jackets",
    "image": "/src/assets/products/p7781.jpg"
  },
  {
    "id": "p7782",
    "name": "Off-White Arrow Print Coach Jacket",
    "originalPrice": 29999,
    "price": 6000,
    "rating": 4.9,
    "category": "Jackets",
    "image": "/src/assets/products/p7782.jpg"
  },
  {
    "id": "p7783",
    "name": "Moncler Grenoble Down Jacket",
    "originalPrice": 38999,
    "price": 7800,
    "rating": 5.0,
    "category": "Jackets",
    "image": "/src/assets/products/p7783.jpg"
  },
  {
    "id": "p7784",
    "name": "Stone Island Shadow Project Jacket",
    "originalPrice": 31500,
    "price": 6300,
    "rating": 4.9,
    "category": "Jackets",
    "image": "/src/assets/products/p7784.jpg"
  },
  {
    "id": "p7785",
    "name": "Nike x Travis Scott Cactus Jack Bomber",
    "originalPrice": 18999,
    "price": 3800,
    "rating": 4.8,
    "category": "Jackets",
    "image": "/src/assets/products/p7785.jpg"
  },
  {
    "id": "p7786",
    "name": "Adidas Originals Varsity Jacket",
    "originalPrice": 8900,
    "price": 1800,
    "rating": 4.7,
    "category": "Jackets",
    "image": "/src/assets/products/p7786.jpg"
  },
  {
    "id": "p7787",
    "name": "Puma x Ferrari Racing Jacket",
    "originalPrice": 9800,
    "price": 1950,
    "rating": 4.6,
    "category": "Jackets",
    "image": "/src/assets/products/p7787.jpg"
  },
  {
    "id": "p7788",
    "name": "Canada Goose Hybridge Lite Down Jacket",
    "originalPrice": 45999,
    "price": 9200,
    "rating": 5.0,
    "category": "Jackets",
    "image": "/src/assets/products/p7788.jpg"
  },
  {
    "id": "p81",
    "name": "Levi\u2019s 511 Slim Fit Jeans",
    "originalPrice": 4200,
    "price": 850,
    "rating": 4.5,
    "category": "Pants",
    "image": "/src/assets/products/p81.jpg"
  },
  {
    "id": "p82",
    "name": "Wrangler Authentics Straight Fit Denim",
    "originalPrice": 3900,
    "price": 800,
    "rating": 4.4,
    "category": "Pants",
    "image": "/src/assets/products/p82.jpg"
  },
  {
    "id": "p83",
    "name": "Lee Cooper Comfort Stretch Jeans",
    "originalPrice": 3700,
    "price": 750,
    "rating": 4.3,
    "category": "Pants",
    "image": "/src/assets/products/p83.jpg"
  },
  {
    "id": "p84",
    "name": "Jack & Jones Skinny Fit Black Jeans",
    "originalPrice": 4600,
    "price": 900,
    "rating": 4.5,
    "category": "Pants",
    "image": "/src/assets/products/p84.jpg"
  },
  {
    "id": "p85",
    "name": "H&M Cargo Utility Pants",
    "originalPrice": 3500,
    "price": 700,
    "rating": 4.3,
    "category": "Pants",
    "image": "/src/assets/products/p85.jpg"
  },
  {
    "id": "p86",
    "name": "ZARA Slim Fit Chino Trousers",
    "originalPrice": 4900,
    "price": 1000,
    "rating": 4.6,
    "category": "Pants",
    "image": "/src/assets/products/p86.jpg"
  },
  {
    "id": "p87",
    "name": "Calvin Klein Relaxed Fit Denim",
    "originalPrice": 7200,
    "price": 1450,
    "rating": 4.7,
    "category": "Pants",
    "image": "/src/assets/products/p87.jpg"
  },
  {
    "id": "p88",
    "name": "Tommy Hilfiger Heritage Cotton Pants",
    "originalPrice": 6900,
    "price": 1400,
    "rating": 4.7,
    "category": "Pants",
    "image": "/src/assets/products/p88.jpg"
  },
  {
    "id": "p89",
    "name": "Adidas Originals 3-Stripes Joggers",
    "originalPrice": 4100,
    "price": 800,
    "rating": 4.4,
    "category": "Pants",
    "image": "/src/assets/products/p89.jpg"
  },
  {
    "id": "p90",
    "name": "Nike Tech Fleece Jogger Pants",
    "originalPrice": 5300,
    "price": 1050,
    "rating": 4.8,
    "category": "Pants",
    "image": "/src/assets/products/p90.jpg"
  },
  {
    "id": "p8881",
    "name": "Gucci GG Monogram Denim Jeans",
    "originalPrice": 24999,
    "price": 5000,
    "rating": 4.9,
    "category": "Pants",
    "image": "/src/assets/products/p8881.jpg"
  },
  {
    "id": "p8882",
    "name": "Louis Vuitton Slim Fit Cotton Pants",
    "originalPrice": 32999,
    "price": 6600,
    "rating": 5.0,
    "category": "Pants",
    "image": "/src/assets/products/p8882.jpg"
  },
  {
    "id": "p8883",
    "name": "Balmain Paris Moto Biker Jeans",
    "originalPrice": 45999,
    "price": 9200,
    "rating": 5.0,
    "category": "Pants",
    "image": "/src/assets/products/p8883.jpg"
  },
  {
    "id": "p8884",
    "name": "Diesel D-Contrac Skinny Fit Jeans",
    "originalPrice": 8900,
    "price": 1800,
    "rating": 4.7,
    "category": "Pants",
    "image": "/src/assets/products/p8884.jpg"
  },
  {
    "id": "p8885",
    "name": "Off-White Diagonal Stripe Sweatpants",
    "originalPrice": 28999,
    "price": 5800,
    "rating": 4.9,
    "category": "Pants",
    "image": "/src/assets/products/p8885.jpg"
  },
  {
    "id": "p8886",
    "name": "Versace Baroque Print Track Pants",
    "originalPrice": 25999,
    "price": 5200,
    "rating": 4.9,
    "category": "Pants",
    "image": "/src/assets/products/p8886.jpg"
  },
  {
    "id": "p8887",
    "name": "Fear of God Essentials Sweatpants",
    "originalPrice": 17999,
    "price": 3600,
    "rating": 4.8,
    "category": "Pants",
    "image": "/src/assets/products/p8887.jpg"
  },
  {
    "id": "p8888",
    "name": "Amiri Distressed Skinny Jeans",
    "originalPrice": 35999,
    "price": 7200,
    "rating": 5.0,
    "category": "Pants",
    "image": "/src/assets/products/p8888.jpg"
  },
  {
    "id": "p8889",
    "name": "Palm Angels Track Pants",
    "originalPrice": 26999,
    "price": 5400,
    "rating": 4.9,
    "category": "Pants",
    "image": "/src/assets/products/p8889.jpg"
  },
  {
    "id": "p8890",
    "name": "Prada Re-Nylon Straight Fit Pants",
    "originalPrice": 38999,
    "price": 7800,
    "rating": 5.0,
    "category": "Pants",
    "image": "/src/assets/products/p8890.jpg"
  },
  // Perfume for Women
{ id: "p91", name: "1 Million Green 100ML", originalPrice: 7998, price: 4999, rating: 4.5, category: "Perfume for Women", image: "/src/assets/products/p91.jpg" },
{ id: "p92", name: "Burberry London EDP", originalPrice: 7998, price: 4999, rating: 4.6, category: "Perfume for Women", image: "/src/assets/products/p92.jpg" },
{ id: "p93", name: "Burberry Weekend EDP 100ML", originalPrice: 7998, price: 4999, rating: 4.4, category: "Perfume for Women", image: "/src/assets/products/p93.jpg" },
{ id: "p94", name: "Carolina Herrera Good Girl New York", originalPrice: 7998, price: 4999, rating: 4.7, category: "Perfume for Women", image: "/src/assets/products/p94.jpg" },
{ id: "p95", name: "Carolina Herrera Dot Drama Gold Edition", originalPrice: 7998, price: 4999, rating: 4.5, category: "Perfume for Women", image: "/src/assets/products/p95.jpg" },
{ id: "p96", name: "Carolina Herrera Good Girl 80ML", originalPrice: 7998, price: 4999, rating: 4.6, category: "Perfume for Women", image: "/src/assets/products/p96.jpg" },
{ id: "p97", name: "Creed Spring Flower EDP 100ML", originalPrice: 7998, price: 4999, rating: 4.8, category: "Perfume for Women", image: "/src/assets/products/p97.jpg" },
{ id: "p98", name: "Dolce & Gabbana Fruit Collection", originalPrice: 7998, price: 4999, rating: 4.5, category: "Perfume for Women", image: "/src/assets/products/p98.jpg" },
{ id: "p99", name: "Giorgio Armani Si Intense EDP 100ML", originalPrice: 7998, price: 4999, rating: 4.7, category: "Perfume for Women", image: "/src/assets/products/p99.jpg" },
{ id: "p100", name: "Gucci Flora Gorgeous Magnolia EDP", originalPrice: 7998, price: 4999, rating: 4.6, category: "Perfume for Women", image: "/src/assets/products/p100.jpg" },
{ id: "p101", name: "Gucci Bamboo Pink EDP 70ML", originalPrice: 7998, price: 4999, rating: 4.5, category: "Perfume for Women", image: "/src/assets/products/p101.jpg" },
{ id: "p102", name: "Jean Paul Gaultier Elixir Absolu EDP", originalPrice: 7998, price: 4999, rating: 4.7, category: "Perfume for Women", image: "/src/assets/products/p102.jpg" },
{ id: "p103", name: "Louis Vuitton Le Jour Se Leve 100ML", originalPrice: 7998, price: 4999, rating: 4.6, category: "Perfume for Women", image: "/src/assets/products/p103.jpg" },
{ id: "p104", name: "Paco Rabanne Fame Eau De Parfum", originalPrice: 7998, price: 4999, rating: 4.8, category: "Perfume for Women", image: "/src/assets/products/p104.jpg" },
{ id: "p105", name: "Portraits Penhaligons Lord George", originalPrice: 7998, price: 4999, rating: 4.4, category: "Perfume for Women", image: "/src/assets/products/p105.jpg" },
{ id: "p106", name: "Prada Milano Paradoxe EDP 90ML", originalPrice: 7998, price: 4999, rating: 4.7, category: "Perfume for Women", image: "/src/assets/products/p106.jpg" },
{ id: "p107", name: "Jean Paul Gaultier La Belle Fleur Terrible", originalPrice: 7998, price: 4999, rating: 4.6, category: "Perfume for Women", image: "/src/assets/products/p107.jpg" },
{ id: "p108", name: "Yves Saint Laurent Libre Le Parfum", originalPrice: 7998, price: 4999, rating: 4.7, category: "Perfume for Women", image: "/src/assets/products/p108.jpg" },
{ id: "p109", name: "Tom Ford Tobacco Vanille EDP 100ML", originalPrice: 7998, price: 4999, rating: 4.8, category: "Perfume for Women", image: "/src/assets/products/p109.jpg" },
{ id: "p110", name: "Tom Ford Electric Cherry 100ML", originalPrice: 7998, price: 4999, rating: 4.8, category: "Perfume for Women", image: "/src/assets/products/p110.jpg" },
{ id: "p111", name: "Versace Yellow Diamond 90ML", originalPrice: 7998, price: 4999, rating: 4.6, category: "Perfume for Women", image: "/src/assets/products/p111.jpg" },
{ id: "p112", name: "Victoria’s Secret Dream Angel EDP 100ML", originalPrice: 7998, price: 4999, rating: 4.5, category: "Perfume for Women", image: "/src/assets/products/p112.jpg" },
{ id: "p113", name: "YSL Manifesto EDP", originalPrice: 7998, price: 4999, rating: 4.7, category: "Perfume for Women", image: "/src/assets/products/p113.jpg" },
{ id: "p114", name: "Premium Dior Addict Eau de Parfum", originalPrice: 7998, price: 4999, rating: 4.6, category: "Perfume for Women", image: "/src/assets/products/p114.jpg" },

// Perfume for Men
{ id: "p115", name: "212 VIP Black Own The Party NUC EDP", originalPrice: 11198, price: 6999, rating: 4.5, category: "Perfume for Men", image: "/src/assets/products/p115.jpg" },
{ id: "p116", name: "212 Sexy Men Eau De Toilette", originalPrice: 11200, price: 7000, rating: 4.6, category: "Perfume for Men", image: "/src/assets/products/p116.jpg" },
{ id: "p117", name: "Azzaro Forever Wanted Golden Edition", originalPrice: 10398, price: 6499, rating: 4.5, category: "Perfume for Men", image: "/src/assets/products/p117.jpg" },
{ id: "p118", name: "Carolina Herrera Bad Boy New York 100ML", originalPrice: 9598, price: 5999, rating: 4.6, category: "Perfume for Men", image: "/src/assets/products/p118.jpg" },
{ id: "p119", name: "Diesel Only The Brave Black EDP 100ML", originalPrice: 7998, price: 4999, rating: 4.4, category: "Perfume for Men", image: "/src/assets/products/p119.jpg" },
{ id: "p120", name: "Diptyque L’Ombre Dans L’Eau EDP 75ML", originalPrice: 8798, price: 5499, rating: 4.5, category: "Perfume for Men", image: "/src/assets/products/p120.jpg" },
{ id: "p121", name: "Diptyque Philosykos EDP 75ML", originalPrice: 7840, price: 4900, rating: 4.3, category: "Perfume for Men", image: "/src/assets/products/p121.jpg" },
{ id: "p122", name: "Hugo Boss Bottled Elixir 100ML", originalPrice: 7998, price: 4999, rating: 4.6, category: "Perfume for Men", image: "/src/assets/products/p122.jpg" },
{ id: "p123", name: "Invictus Paco Rabanne", originalPrice: 7998, price: 4999, rating: 4.7, category: "Perfume for Men", image: "/src/assets/products/p123.jpg" },
{ id: "p124", name: "Jaguar Classic Chromite EDP 100ML", originalPrice: 7998, price: 4999, rating: 4.4, category: "Perfume for Men", image: "/src/assets/products/p124.jpg" },

// Men's Watch (Updated)
{ id: "p125", name: "Michael Kors Lexington Premium", originalPrice: 12640, price: 7900, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p125.jpg" },
{ id: "p126", name: "Hublot Automatic Open Back AAA", originalPrice: 8320, price: 5200, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p126.jpg" },
{ id: "p127", name: "Tissot Chemin des Tourelles Automatic Green", originalPrice: 15680, price: 9800, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p127.jpg" },
{ id: "p128", name: "Armani Exchange AX2418 Automatic", originalPrice: 6880, price: 4300, rating: 4.1, category: "Men’s Watch", image: "/src/assets/products/p128.jpg" },
{ id: "p129", name: "Patek Philippe Nautilus Automatic Copper Blue", originalPrice: 10232, price: 6395, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p129.jpg" },
{ id: "p130", name: "Seiko 5 Sports Automatic", originalPrice: 9598, price: 5999, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p130.jpg" },
{ id: "p131", name: "Rado Automatic Watch", originalPrice: 14398, price: 8999, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p131.jpg" },
{ id: "p132", name: "Casio Edifice ECB-2000", originalPrice: 10880, price: 6800, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p132.jpg" },
{ id: "p133", name: "Citizen Tsuyosa Open Heart Premium Automatic", originalPrice: 10880, price: 6800, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p133.jpg" },
{ id: "p134", name: "Hublot BigBang Fusion-1886", originalPrice: 7840, price: 4900, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p134.jpg" },
{ id: "p135", name: "Audemars Piguet Royal Oak Quartz", originalPrice: 10398, price: 6499, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p135.jpg" },
{ id: "p136", name: "Fossil ME3061 Automatic (Open Back)", originalPrice: 10240, price: 6400, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p136.jpg" },
{ id: "p137", name: "Audemars Piguet Royal Oak Quartz Copper-White", originalPrice: 9118, price: 5699, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p137.jpg" },
{ id: "p138", name: "Tommy Hilfiger Decker-11458", originalPrice: 8480, price: 5300, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p138.jpg" },
{ id: "p139", name: "Corum Watch", originalPrice: 9598, price: 5999, rating: 4.1, category: "Men’s Watch", image: "/src/assets/products/p139.jpg" },
{ id: "p140", name: "Michael Kors Lexington Premium II", originalPrice: 12480, price: 7800, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p140.jpg" },
{ id: "p141", name: "Rait Pastar Automatic 85 KB", originalPrice: 9920, price: 6200, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p141.jpg" },
{ id: "p142", name: "Edifice Armani Exchange Watch", originalPrice: 7200, price: 4500, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p142.jpg" },
{ id: "p143", name: "Fossil Automatic Watch", originalPrice: 8000, price: 5000, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p143.jpg" },
{ id: "p144", name: "Tissot 1853 Chemin", originalPrice: 7838, price: 4899, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p144.jpg" },
{ id: "p145", name: "Hublot BigBang Tourbillon J1509", originalPrice: 6400, price: 4000, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p145.jpg" },
{ id: "p146", name: "Franck Muller Vanguard Crazy Hours", originalPrice: 9598, price: 5999, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p146.jpg" },
{ id: "p147", name: "Emporio Armani Chronograph Chrono Worlang", originalPrice: 7998, price: 4999, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p147.jpg" },
{ id: "p148", name: "Fossil Townsman Leather", originalPrice: 9440, price: 5900, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p148.jpg" },
{ id: "p149", name: "Rolex Oyster Perpetual Submarine Automatic", originalPrice: 9280, price: 5800, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p149.jpg" },
{ id: "p150", name: "Hublot Automatic Open Back AAA (Gold Edition)", originalPrice: 12798, price: 7999, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p150.jpg" },
{ id: "p151", name: "G-Shock GA 2100 Black (All Working)", originalPrice: 9438, price: 5899, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p151.jpg" },
{ id: "p152", name: "Richard Mille McLaren Black Chronograph", originalPrice: 12480, price: 7800, rating: 4.6, category: "Men’s Watch", image: "/src/assets/products/p152.jpg" },
{ id: "p153", name: "Audemars Piguet Royal Oak Automatic", originalPrice: 10720, price: 6700, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p153.jpg" },
{ id: "p154", name: "Armani Ceramic Watch", originalPrice: 7998, price: 4999, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p154.jpg" },
{ id: "p155", name: "Patek Philippe Skeleton Automatic J1502", originalPrice: 8000, price: 5000, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p155.jpg" },
{ id: "p156", name: "Rado Captain Cook Automatic", originalPrice: 14398, price: 8999, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p156.jpg" },
{ id: "p157", name: "Breguet Double Engine Brown Copper", originalPrice: 10880, price: 6800, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p157.jpg" },
{ id: "p158", name: "Tissot 1853 PRX Powermatic Quartz", originalPrice: 11200, price: 7000, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p158.jpg" },
{ id: "p159", name: "Tommy Hilfiger Weston Automatic AAA Open Back", originalPrice: 11040, price: 6900, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p159.jpg" },
{ id: "p160", name: "Tommy Hilfiger Decker J1521", originalPrice: 9598, price: 5999, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p160.jpg" },
{ id: "p161", name: "Tommy Hilfiger Automatic Watch", originalPrice: 10080, price: 6300, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p161.jpg" },
{ id: "p162", name: "Fossil Townsman Chain Belt", originalPrice: 9438, price: 5899, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p162.jpg" },
{ id: "p163", name: "Michael Kors Lexington Premium III", originalPrice: 10880, price: 6800, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p163.jpg" },
{ id: "p164", name: "Rolex Just Date Automatic Watch", originalPrice: 10880, price: 6800, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p164.jpg" },
{ id: "p165", name: "Swatch Neon Jelly White Chronograph", originalPrice: 8000, price: 5000, rating: 4.1, category: "Men’s Watch", image: "/src/assets/products/p165.jpg" },
{ id: "p166", name: "G-Shock GM 2100 All Working", originalPrice: 6400, price: 4000, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p166.jpg" },
{ id: "p167", name: "Patek Philippe Nautilus Silver Black", originalPrice: 10880, price: 6800, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p167.jpg" },
{ id: "p168", name: "Citizen Tsuyosa Open Heart Automatic", originalPrice: 10880, price: 6800, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p168.jpg" },
{ id: "p169", name: "Tissot 1853 Chemin Chronograph", originalPrice: 7998, price: 4999, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p169.jpg" },
{ id: "p170", name: "Diesel 13 Bar Big Daddy 2-Tone Copper Black", originalPrice: 11200, price: 7000, rating: 4.2, category: "Men’s Watch", image: "/src/assets/products/p170.jpg" },
{ id: "p171", name: "Armani Exchange Chronograph", originalPrice: 9280, price: 5800, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p171.jpg" },
{ id: "p172", name: "Casio Edifice ECB-2000 Chronograph", originalPrice: 11200, price: 7000, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p172.jpg" },
{ id: "p173", name: "Emporio Armani Meccanico Automatic", originalPrice: 9598, price: 5999, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p173.jpg" },
{ id: "p174", name: "Cartier Ballon Automatic", originalPrice: 9600, price: 6000, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p174.jpg" },
{ id: "p175", name: "Tissot PRC 200 Chronograph", originalPrice: 8960, price: 5600, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p175.jpg" },
{ id: "p176", name: "Versace Aion Chronograph", originalPrice: 7680, price: 4800, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p176.jpg" },

// Auto-filled similar watches till p224
{ id: "p177", name: "Omega Seamaster Diver 300M", originalPrice: 14398, price: 8999, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p177.jpg" },
{ id: "p178", name: "Rolex Daytona Gold Edition", originalPrice: 15998, price: 9999, rating: 4.7, category: "Men’s Watch", image: "/src/assets/products/p178.jpg" },
{ id: "p179", name: "Tag Heuer Carrera Automatic", originalPrice: 13198, price: 8249, rating: 4.6, category: "Men’s Watch", image: "/src/assets/products/p179.jpg" },
{ id: "p180", name: "Breitling Navitimer Chronograph", originalPrice: 15998, price: 9999, rating: 4.7, category: "Men’s Watch", image: "/src/assets/products/p180.jpg" },
{ id: "p181", name: "Tudor Black Bay Heritage", originalPrice: 12798, price: 7999, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p181.jpg" },
{ id: "p182", name: "Longines Master Collection", originalPrice: 14398, price: 8999, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p182.jpg" },
{ id: "p183", name: "Panerai Luminor Marina", originalPrice: 15998, price: 9999, rating: 4.6, category: "Men’s Watch", image: "/src/assets/products/p183.jpg" },
{ id: "p184", name: "Montblanc 1858 Automatic Chronograph", originalPrice: 13198, price: 8249, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p184.jpg" },
{ id: "p185", name: "Rolex Yacht-Master II", originalPrice: 15998, price: 9999, rating: 4.7, category: "Men’s Watch", image: "/src/assets/products/p185.jpg" },
{ id: "p186", name: "Omega Speedmaster Moonwatch", originalPrice: 14398, price: 8999, rating: 4.6, category: "Men’s Watch", image: "/src/assets/products/p186.jpg" },
{ id: "p187", name: "Tag Heuer Monaco Chronograph", originalPrice: 12798, price: 7999, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p187.jpg" },
{ id: "p188", name: "Tissot PRX Automatic", originalPrice: 12798, price: 7999, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p188.jpg" },
{ id: "p189", name: "Longines HydroConquest", originalPrice: 15998, price: 9999, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p189.jpg" },
{ id: "p190", name: "Rado Centrix Automatic", originalPrice: 14398, price: 8999, rating: 4.6, category: "Men’s Watch", image: "/src/assets/products/p190.jpg" },
{ id: "p191", name: "Rolex Submariner Date", originalPrice: 15998, price: 9999, rating: 4.8, category: "Men’s Watch", image: "/src/assets/products/p191.jpg" },
{ id: "p192", name: "Omega De Ville Prestige", originalPrice: 14398, price: 8999, rating: 4.6, category: "Men’s Watch", image: "/src/assets/products/p192.jpg" },
{ id: "p193", name: "Tag Heuer Formula 1", originalPrice: 12798, price: 7999, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p193.jpg" },
{ id: "p194", name: "Breitling Superocean Heritage", originalPrice: 15998, price: 9999, rating: 4.7, category: "Men’s Watch", image: "/src/assets/products/p194.jpg" },
{ id: "p195", name: "Panerai Submersible", originalPrice: 14398, price: 8999, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p195.jpg" },
{ id: "p196", name: "Tudor Pelagos FXD", originalPrice: 14398, price: 8999, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p196.jpg" },
{ id: "p197", name: "IWC Schaffhausen Pilot’s Watch", originalPrice: 15998, price: 9999, rating: 4.7, category: "Men’s Watch", image: "/src/assets/products/p197.jpg" },
{ id: "p198", name: "Jaeger-LeCoultre Reverso Classic", originalPrice: 14398, price: 8999, rating: 4.6, category: "Men’s Watch", image: "/src/assets/products/p198.jpg" },
{ id: "p199", name: "Rolex Explorer II", originalPrice: 15998, price: 9999, rating: 4.8, category: "Men’s Watch", image: "/src/assets/products/p199.jpg" },
{ id: "p200", name: "Omega Railmaster", originalPrice: 12798, price: 7999, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p200.jpg" },
{ id: "p201", name: "Rado True Thinline Quartz", originalPrice: 14398, price: 8999, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p201.jpg" },
{ id: "p202", name: "Cartier Santos de Cartier", originalPrice: 15998, price: 9999, rating: 4.7, category: "Men’s Watch", image: "/src/assets/products/p202.jpg" },
{ id: "p203", name: "Tissot Gentleman Powermatic 80", originalPrice: 12798, price: 7999, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p203.jpg" },
{ id: "p204", name: "Hamilton Khaki Field Mechanical", originalPrice: 9598, price: 5999, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p204.jpg" },
{ id: "p205", name: "Rolex Milgauss", originalPrice: 15998, price: 9999, rating: 4.7, category: "Men’s Watch", image: "/src/assets/products/p205.jpg" },
{ id: "p206", name: "Omega Constellation Co-Axial", originalPrice: 14398, price: 8999, rating: 4.6, category: "Men’s Watch", image: "/src/assets/products/p206.jpg" },
{ id: "p207", name: "Tag Heuer Autavia Chronograph", originalPrice: 13198, price: 8249, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p207.jpg" },
{ id: "p208", name: "Longines Spirit Automatic", originalPrice: 14398, price: 8999, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p208.jpg" },
{ id: "p209", name: "Tudor Ranger Heritage", originalPrice: 12798, price: 7999, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p209.jpg" },
{ id: "p210", name: "Omega Seamaster Aqua Terra", originalPrice: 15998, price: 9999, rating: 4.7, category: "Men’s Watch", image: "/src/assets/products/p210.jpg" },
{ id: "p211", name: "Rolex GMT Master II", originalPrice: 15998, price: 9999, rating: 4.8, category: "Men’s Watch", image: "/src/assets/products/p211.jpg" },
{ id: "p212", name: "Breitling Chronomat B01", originalPrice: 15998, price: 9999, rating: 4.6, category: "Men’s Watch", image: "/src/assets/products/p212.jpg" },
{ id: "p213", name: "Omega Speedmaster Racing", originalPrice: 14398, price: 8999, rating: 4.6, category: "Men’s Watch", image: "/src/assets/products/p213.jpg" },
{ id: "p214", name: "Tissot Heritage Visodate Automatic", originalPrice: 12798, price: 7999, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p214.jpg" },
{ id: "p215", name: "Hamilton Jazzmaster Viewmatic", originalPrice: 9598, price: 5999, rating: 4.3, category: "Men’s Watch", image: "/src/assets/products/p215.jpg" },
{ id: "p216", name: "Longines Record Collection", originalPrice: 14398, price: 8999, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p216.jpg" },
{ id: "p217", name: "Rado HyperChrome Automatic", originalPrice: 14398, price: 8999, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p217.jpg" },
{ id: "p218", name: "Cartier Drive de Cartier", originalPrice: 15998, price: 9999, rating: 4.6, category: "Men’s Watch", image: "/src/assets/products/p218.jpg" },
{ id: "p219", name: "IWC Portugieser Automatic", originalPrice: 15998, price: 9999, rating: 4.7, category: "Men’s Watch", image: "/src/assets/products/p219.jpg" },
{ id: "p220", name: "Tag Heuer Link Chronograph", originalPrice: 13198, price: 8249, rating: 4.4, category: "Men’s Watch", image: "/src/assets/products/p220.jpg" },
{ id: "p221", name: "Omega Seamaster Planet Ocean", originalPrice: 15998, price: 9999, rating: 4.8, category: "Men’s Watch", image: "/src/assets/products/p221.jpg" },
{ id: "p222", name: "Rolex Air-King", originalPrice: 15998, price: 9999, rating: 4.7, category: "Men’s Watch", image: "/src/assets/products/p222.jpg" },
{ id: "p223", name: "Longines Elegance Automatic", originalPrice: 12798, price: 7999, rating: 4.5, category: "Men’s Watch", image: "/src/assets/products/p223.jpg" },
{ id: "p224", name: "Omega Seamaster 300 Heritage", originalPrice: 15998, price: 9999, rating: 4.6, category: "Men’s Watch", image: "/src/assets/products/p224.jpg" },

// Women's Watch (Updated)
/* { id: "p229", name: "Michael Kors Ladies Watch", originalPrice: 8000, price: 5000, rating: 4.3, category: "Women’s Watch", image: "/src/assets/products/p229.jpg" },
{ id: "p230", name: "Michael Kors For Her AAA", originalPrice: 12798, price: 7999, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p230.jpg" },
{ id: "p231", name: "Michael Kors For Her AAA (Edition II)", originalPrice: 14398, price: 8999, rating: 4.5, category: "Women’s Watch", image: "/src/assets/products/p231.jpg" },
{ id: "p232", name: "Michael Kors Bradshaw", originalPrice: 6400, price: 4000, rating: 4.2, category: "Women’s Watch", image: "/src/assets/products/p232.jpg" },
{ id: "p233", name: "Michael Kors 100 Series", originalPrice: 11038, price: 6899, rating: 4.3, category: "Women’s Watch", image: "/src/assets/products/p233.jpg" },
{ id: "p234", name: "Michael Kors Ladies Watch Green Dial", originalPrice: 15200, price: 9500, rating: 4.5, category: "Women’s Watch", image: "/src/assets/products/p234.jpg" },
{ id: "p235", name: "Gucci 25H Women’s Watch", originalPrice: 11038, price: 6899, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p235.jpg" },
{ id: "p236", name: "Womens Store Article Watch", originalPrice: 11038, price: 6899, rating: 4.3, category: "Women’s Watch", image: "/src/assets/products/p236.jpg" },
{ id: "p237", name: "Fossil Ladies Watch", originalPrice: 7200, price: 4500, rating: 4.2, category: "Women’s Watch", image: "/src/assets/products/p237.jpg" },
{ id: "p238", name: "Fossi I Tailor I Edition", originalPrice: 12638, price: 7899, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p238.jpg" },
{ id: "p239", name: "Fossi I Tailor II Edition", originalPrice: 12798, price: 7999, rating: 4.3, category: "Women’s Watch", image: "/src/assets/products/p239.jpg" },
{ id: "p240", name: "Emporio Armani For Her", originalPrice: 8960, price: 5600, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p240.jpg" },
{ id: "p241", name: "Emporio Armani AR11245 Japan Quality AAA", originalPrice: 9600, price: 6000, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p241.jpg" },
{ id: "p242", name: "Emporio Armani AR1486 Ceramic", originalPrice: 10720, price: 6700, rating: 4.3, category: "Women’s Watch", image: "/src/assets/products/p242.jpg" },
{ id: "p243", name: "Calvin Klein Women’s Watch", originalPrice: 8000, price: 5000, rating: 4.2, category: "Women’s Watch", image: "/src/assets/products/p243.jpg" },
{ id: "p244", name: "Armani Women’s Watch", originalPrice: 8000, price: 5000, rating: 4.2, category: "Women’s Watch", image: "/src/assets/products/p244.jpg" },

// Extra Women’s Watches (to reach p300)
{ id: "p245", name: "Versace Eros For Women", originalPrice: 11198, price: 6999, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p245.jpg" },
{ id: "p246", name: "Fossil Jacqueline Rose Gold", originalPrice: 10398, price: 6499, rating: 4.3, category: "Women’s Watch", image: "/src/assets/products/p246.jpg" },
{ id: "p247", name: "Michael Kors Parker Chronograph", originalPrice: 11038, price: 6899, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p247.jpg" },
{ id: "p248", name: "Emporio Armani Gianni T-Bar", originalPrice: 11200, price: 7000, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p248.jpg" },
{ id: "p249", name: "Fossil Carlie Mini Watch", originalPrice: 9598, price: 5999, rating: 4.2, category: "Women’s Watch", image: "/src/assets/products/p249.jpg" },
{ id: "p250", name: "Guess Nova Stainless Steel", originalPrice: 10398, price: 6499, rating: 4.3, category: "Women’s Watch", image: "/src/assets/products/p250.jpg" },
{ id: "p251", name: "Michael Kors Runway Slim", originalPrice: 11198, price: 6999, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p251.jpg" },
{ id: "p252", name: "DKNY Soho Two-Tone", originalPrice: 9600, price: 6000, rating: 4.2, category: "Women’s Watch", image: "/src/assets/products/p252.jpg" },
{ id: "p253", name: "Fossil Lyric Hybrid Smartwatch", originalPrice: 12478, price: 7799, rating: 4.3, category: "Women’s Watch", image: "/src/assets/products/p253.jpg" },
{ id: "p254", name: "Michael Kors Mini Darci", originalPrice: 11038, price: 6899, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p254.jpg" },
{ id: "p255", name: "Emporio Armani Retro Slim", originalPrice: 9598, price: 5999, rating: 4.2, category: "Women’s Watch", image: "/src/assets/products/p255.jpg" },
{ id: "p256", name: "Tissot Flamingo Lady", originalPrice: 11998, price: 7499, rating: 4.5, category: "Women’s Watch", image: "/src/assets/products/p256.jpg" },
{ id: "p257", name: "Michael Kors Sofie Pavé", originalPrice: 11038, price: 6899, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p257.jpg" },
{ id: "p258", name: "Guess Luna Blue Dial", originalPrice: 7998, price: 4999, rating: 4.2, category: "Women’s Watch", image: "/src/assets/products/p258.jpg" },
{ id: "p259", name: "Fossil Carlie Mini", originalPrice: 9438, price: 5899, rating: 4.2, category: "Women’s Watch", image: "/src/assets/products/p259.jpg" },
{ id: "p260", name: "Citizen Eco-Drive L Sunrise", originalPrice: 11998, price: 7499, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p260.jpg" },
{ id: "p261", name: "Casio Sheen Crystal Series", originalPrice: 7998, price: 4999, rating: 4.1, category: "Women’s Watch", image: "/src/assets/products/p261.jpg" },
{ id: "p262", name: "Michael Kors Mini Runway Gold", originalPrice: 11198, price: 6999, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p262.jpg" },
{ id: "p263", name: "Gucci G-Timeless Petite", originalPrice: 15998, price: 9999, rating: 4.6, category: "Women’s Watch", image: "/src/assets/products/p263.jpg" },
{ id: "p264", name: "Emporio Armani Ladies Rose Gold", originalPrice: 10398, price: 6499, rating: 4.3, category: "Women’s Watch", image: "/src/assets/products/p264.jpg" },
{ id: "p265", name: "Michael Kors Darci Silver Dial", originalPrice: 11038, price: 6899, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p265.jpg" },
{ id: "p266", name: "Tissot Lovely Square", originalPrice: 11198, price: 6999, rating: 4.3, category: "Women’s Watch", image: "/src/assets/products/p266.jpg" },
{ id: "p267", name: "Fossil Stella Multifunction", originalPrice: 10398, price: 6499, rating: 4.3, category: "Women’s Watch", image: "/src/assets/products/p267.jpg" },
{ id: "p268", name: "Michael Kors Portia Pink Dial", originalPrice: 11198, price: 6999, rating: 4.3, category: "Women’s Watch", image: "/src/assets/products/p268.jpg" },
{ id: "p269", name: "Guess Sparkle Icon", originalPrice: 9598, price: 5999, rating: 4.2, category: "Women’s Watch", image: "/src/assets/products/p269.jpg" },
{ id: "p270", name: "Casio Enticer Ladies Analog", originalPrice: 7998, price: 4999, rating: 4.2, category: "Women’s Watch", image: "/src/assets/products/p270.jpg" }, */
{ id: "p271", name: "Michael Kors Pyper Gold-Tone", originalPrice: 10398, price: 6499, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p271.jpg" },
{ id: "p272", name: "Emporio Armani Classic Quartz", originalPrice: 9598, price: 5999, rating: 4.2, category: "Women’s Watch", image: "/src/assets/products/p272.jpg" },
{ id: "p273", name: "Fossil Carlie Three-Hand Blush", originalPrice: 9438, price: 5899, rating: 4.2, category: "Women’s Watch", image: "/src/assets/products/p273.jpg" },
{ id: "p274", name: "Michael Kors Lauryn Mini", originalPrice: 10398, price: 6499, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p274.jpg" },
{ id: "p275", name: "Guess Pearlized Rose Watch", originalPrice: 7998, price: 4999, rating: 4.1, category: "Women’s Watch", image: "/src/assets/products/p275.jpg" },
{ id: "p276", name: "Casio Vintage Rose Gold Digital", originalPrice: 7998, price: 4999, rating: 4.2, category: "Women’s Watch", image: "/src/assets/products/p276.jpg" },
{ id: "p277", name: "Michael Kors Slim Runway Black Dial", originalPrice: 10398, price: 6499, rating: 4.3, category: "Women’s Watch", image: "/src/assets/products/p277.jpg" },
{ id: "p278", name: "Emporio Armani Chiara Gold-Tone", originalPrice: 11198, price: 6999, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p278.jpg" },
{ id: "p279", name: "Tissot Flamingo Two-Tone", originalPrice: 11198, price: 6999, rating: 4.3, category: "Women’s Watch", image: "/src/assets/products/p279.jpg" },
{ id: "p280", name: "Michael Kors Blair Chronograph", originalPrice: 11998, price: 7499, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p280.jpg" },
{ id: "p281", name: "Guess Mini Soho", originalPrice: 7998, price: 4999, rating: 4.1, category: "Women’s Watch", image: "/src/assets/products/p281.jpg" },
{ id: "p282", name: "Casio Enticer Women’s Silver Dial", originalPrice: 7998, price: 4999, rating: 4.1, category: "Women’s Watch", image: "/src/assets/products/p282.jpg" },
{ id: "p283", name: "Fossil Stella Rose Gold Dial", originalPrice: 9438, price: 5899, rating: 4.2, category: "Women’s Watch", image: "/src/assets/products/p283.jpg" },
{ id: "p284", name: "Michael Kors Whitney Crystal Watch", originalPrice: 11198, price: 6999, rating: 4.5, category: "Women’s Watch", image: "/src/assets/products/p284.jpg" },
{ id: "p285", name: "Emporio Armani Modern Slim", originalPrice: 9598, price: 5999, rating: 4.2, category: "Women’s Watch", image: "/src/assets/products/p285.jpg" },
{ id: "p286", name: "Gucci G-Frame Women’s Watch", originalPrice: 15998, price: 9999, rating: 4.6, category: "Women’s Watch", image: "/src/assets/products/p286.jpg" },
{ id: "p287", name: "Michael Kors Sofie Pavé Chronograph", originalPrice: 11198, price: 6999, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p287.jpg" },
{ id: "p288", name: "Tissot Lovely Diamonds", originalPrice: 11998, price: 7499, rating: 4.5, category: "Women’s Watch", image: "/src/assets/products/p288.jpg" },
{ id: "p289", name: "Fossil Monroe Two-Hand", originalPrice: 9598, price: 5999, rating: 4.2, category: "Women’s Watch", image: "/src/assets/products/p289.jpg" },
{ id: "p290", name: "Casio Sheen Women’s Analog", originalPrice: 7998, price: 4999, rating: 4.2, category: "Women’s Watch", image: "/src/assets/products/p290.jpg" },
{ id: "p291", name: "Michael Kors Mini Sofie", originalPrice: 10398, price: 6499, rating: 4.3, category: "Women’s Watch", image: "/src/assets/products/p291.jpg" },
{ id: "p292", name: "Emporio Armani Modern Ceramica", originalPrice: 11198, price: 6999, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p292.jpg" },
{ id: "p293", name: "Fossil Jacqueline Rose Dial", originalPrice: 9438, price: 5899, rating: 4.2, category: "Women’s Watch", image: "/src/assets/products/p293.jpg" },
{ id: "p294", name: "Tissot Flamingo Pink Strap", originalPrice: 11198, price: 6999, rating: 4.3, category: "Women’s Watch", image: "/src/assets/products/p294.jpg" },
{ id: "p295", name: "Michael Kors Camille Gold-Tone", originalPrice: 11198, price: 6999, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p295.jpg" },
{ id: "p296", name: "Fossil Lyric Hybrid Smartwatch II", originalPrice: 12478, price: 7799, rating: 4.3, category: "Women’s Watch", image: "/src/assets/products/p296.jpg" },
{ id: "p297", name: "Emporio Armani Gianni T-Bar Rose Gold", originalPrice: 11198, price: 6999, rating: 4.3, category: "Women’s Watch", image: "/src/assets/products/p297.jpg" },
{ id: "p298", name: "Michael Kors Pyper Leather", originalPrice: 11198, price: 6999, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p298.jpg" },
{ id: "p299", name: "Gucci Diamantissima Quartz", originalPrice: 15998, price: 9999, rating: 4.6, category: "Women’s Watch", image: "/src/assets/products/p299.jpg" },
{ id: "p300", name: "Michael Kors Parker Chronograph Silver", originalPrice: 11198, price: 6999, rating: 4.4, category: "Women’s Watch", image: "/src/assets/products/p300.jpg" },

// Men's Sunglasses (Updated)
{ id: "p301", name: "Balmain Designer AquaLuxury Shades", originalPrice: 9600, price: 6000, rating: 4.4, category: "Men’s Sunglasses", image: "/src/assets/products/p301.jpg" },
{ id: "p302", name: "Burberry 2114", originalPrice: 8800, price: 5500, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p302.jpg" },
{ id: "p303", name: "Premium Glossy Frame Sunglass", originalPrice: 7200, price: 4500, rating: 4.2, category: "Men’s Sunglasses", image: "/src/assets/products/p303.jpg" },
{ id: "p304", name: "Burberry 23212 Tiger Edition", originalPrice: 5598, price: 3499, rating: 4.2, category: "Men’s Sunglasses", image: "/src/assets/products/p304.jpg" },
{ id: "p305", name: "Burberry Wayfarer White Black", originalPrice: 7998, price: 4999, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p305.jpg" },
{ id: "p306", name: "Calvin Klein Y06 White Black", originalPrice: 6398, price: 3999, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p306.jpg" },
{ id: "p307", name: "Celine 556 Silver Blue", originalPrice: 6400, price: 4000, rating: 4.2, category: "Men’s Sunglasses", image: "/src/assets/products/p307.jpg" },
{ id: "p308", name: "Chanel 1326 Black White", originalPrice: 6398, price: 3999, rating: 4.4, category: "Men’s Sunglasses", image: "/src/assets/products/p308.jpg" },
{ id: "p309", name: "Chrome Hearts 8216 Black", originalPrice: 6398, price: 3999, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p309.jpg" },
{ id: "p310", name: "Christian Dior White Star Edition", originalPrice: 7998, price: 4999, rating: 4.5, category: "Men’s Sunglasses", image: "/src/assets/products/p310.jpg" },
{ id: "p311", name: "David Beckham 2208 Water Brown Green", originalPrice: 7998, price: 4999, rating: 4.4, category: "Men’s Sunglasses", image: "/src/assets/products/p311.jpg" },
{ id: "p312", name: "Dita 0125 Water Black", originalPrice: 7838, price: 4899, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p312.jpg" },
{ id: "p313", name: "Dolce & Gabbana 6187 Premium Sunglass", originalPrice: 8800, price: 5500, rating: 4.4, category: "Men’s Sunglasses", image: "/src/assets/products/p313.jpg" },
{ id: "p314", name: "Dolce & Gabbana White Mirror Luxury Shade 4106", originalPrice: 7998, price: 4999, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p314.jpg" },
{ id: "p315", name: "Jacques Marie Mage 3959 Blue White Candy", originalPrice: 6398, price: 3999, rating: 4.2, category: "Men’s Sunglasses", image: "/src/assets/products/p315.jpg" },
{ id: "p316", name: "Louis Vuitton 1502 Brown", originalPrice: 7200, price: 4500, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p316.jpg" },
{ id: "p317", name: "Dolce & Gabbana 6187 Water Black", originalPrice: 7998, price: 4999, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p317.jpg" },
{ id: "p318", name: "Emporio Armani 219 Grey Green", originalPrice: 5758, price: 3599, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p318.jpg" },
{ id: "p319", name: "Louis Vuitton 6129 Premium Sunglass", originalPrice: 12800, price: 8000, rating: 4.5, category: "Men’s Sunglasses", image: "/src/assets/products/p319.jpg" },
{ id: "p320", name: "Gucci 1390 Premium Brown", originalPrice: 9600, price: 6000, rating: 4.4, category: "Men’s Sunglasses", image: "/src/assets/products/p320.jpg" },
{ id: "p321", name: "Louis Vuitton Millionaire Edition 96006", originalPrice: 10878, price: 6799, rating: 4.5, category: "Men’s Sunglasses", image: "/src/assets/products/p321.jpg" },
{ id: "p322", name: "Gucci Green-Black Shaded Lens 8949", originalPrice: 6398, price: 3999, rating: 4.2, category: "Men’s Sunglasses", image: "/src/assets/products/p322.jpg" },
{ id: "p323", name: "Hugo Boss 1310 Shine Black", originalPrice: 7998, price: 4999, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p323.jpg" },
{ id: "p324", name: "Louis Vuitton 1005 Black Gold Plano", originalPrice: 4798, price: 2999, rating: 4.2, category: "Men’s Sunglasses", image: "/src/assets/products/p324.jpg" },
{ id: "p325", name: "Gucci 1295 Ice Black", originalPrice: 7998, price: 4999, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p325.jpg" },
{ id: "p326", name: "Louis Vuitton 4577 Ice Black", originalPrice: 7998, price: 4999, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p326.jpg" },
{ id: "p327", name: "Gucci 2417 Ice Black", originalPrice: 7998, price: 4999, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p327.jpg" },
{ id: "p328", name: "Louis Vuitton 96006 Grey", originalPrice: 9598, price: 5999, rating: 4.4, category: "Men’s Sunglasses", image: "/src/assets/products/p328.jpg" },
{ id: "p329", name: "Gucci 5106 Black Tiger", originalPrice: 6398, price: 3999, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p329.jpg" },
{ id: "p330", name: "Marc Jacobs All Brown Luxury Shades 2008", originalPrice: 6398, price: 3999, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p330.jpg" },
{ id: "p331", name: "Gucci 6186 Purple", originalPrice: 7998, price: 4999, rating: 4.4, category: "Men’s Sunglasses", image: "/src/assets/products/p331.jpg" },
{ id: "p332", name: "Marc Jacobs All Grey Luxury Shades 6008", originalPrice: 7998, price: 4999, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p332.jpg" },
{ id: "p333", name: "Marc Jacobs Kuboraum Black Plano", originalPrice: 9598, price: 5999, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p333.jpg" },
{ id: "p334", name: "Miu Miu 2049 Black", originalPrice: 7358, price: 4599, rating: 4.2, category: "Men’s Sunglasses", image: "/src/assets/products/p334.jpg" },
{ id: "p335", name: "Miu Miu 1423 Gold Black", originalPrice: 3198, price: 1999, rating: 4.1, category: "Men’s Sunglasses", image: "/src/assets/products/p335.jpg" },
{ id: "p336", name: "Moscot 1120 Water", originalPrice: 6398, price: 3999, rating: 4.2, category: "Men’s Sunglasses", image: "/src/assets/products/p336.jpg" },
{ id: "p337", name: "Oakley Sport Blue Luxury", originalPrice: 8800, price: 5500, rating: 4.4, category: "Men’s Sunglasses", image: "/src/assets/products/p337.jpg" },
{ id: "p338", name: "Oakley 3384 Grey Orange Mercury", originalPrice: 9598, price: 5999, rating: 4.4, category: "Men’s Sunglasses", image: "/src/assets/products/p338.jpg" },
{ id: "p339", name: "Oakley 4929 Blue Mercury", originalPrice: 9598, price: 5999, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p339.jpg" },
{ id: "p340", name: "Oakley 8241 Blue Red Day", originalPrice: 9598, price: 5999, rating: 4.4, category: "Men’s Sunglasses", image: "/src/assets/products/p340.jpg" },
{ id: "p341", name: "Oakley 9280 Black Blue Pink", originalPrice: 9598, price: 5999, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p341.jpg" },
{ id: "p342", name: "Oakley 9280 Neo Blue Revo", originalPrice: 7998, price: 4999, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p342.jpg" },
{ id: "p343", name: "Oakley S3 Black Mirror", originalPrice: 9598, price: 5999, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p343.jpg" },
{ id: "p344", name: "Palm Angels All Black Divine", originalPrice: 7998, price: 4999, rating: 4.4, category: "Men’s Sunglasses", image: "/src/assets/products/p344.jpg" },
{ id: "p345", name: "Ray-Ban Clubmaster Classic", originalPrice: 10398, price: 6499, rating: 4.5, category: "Men’s Sunglasses", image: "/src/assets/products/p345.jpg" },
{ id: "p346", name: "Prada Linea Rossa Sport", originalPrice: 10398, price: 6499, rating: 4.4, category: "Men’s Sunglasses", image: "/src/assets/products/p346.jpg" },
{ id: "p347", name: "Tom Ford Leo Black Edition", originalPrice: 11198, price: 6999, rating: 4.4, category: "Men’s Sunglasses", image: "/src/assets/products/p347.jpg" },
{ id: "p348", name: "Versace Medusa Oversized", originalPrice: 11198, price: 6999, rating: 4.5, category: "Men’s Sunglasses", image: "/src/assets/products/p348.jpg" },
{ id: "p349", name: "Police Navigator Silver", originalPrice: 9598, price: 5999, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p349.jpg" },
{ id: "p350", name: "Fendi FF0150 Aviator", originalPrice: 10398, price: 6499, rating: 4.4, category: "Men’s Sunglasses", image: "/src/assets/products/p350.jpg" },
{ id: "p351", name: "Ray-Ban Justin Matte Black", originalPrice: 9598, price: 5999, rating: 4.4, category: "Men’s Sunglasses", image: "/src/assets/products/p351.jpg" },
{ id: "p352", name: "Prada Sport Shield Blue Lens", originalPrice: 9598, price: 5999, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p352.jpg" },
{ id: "p353", name: "Tommy Hilfiger Square Frame", originalPrice: 7998, price: 4999, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p353.jpg" },
{ id: "p354", name: "Gucci GG1059 Havana Lens", originalPrice: 11198, price: 6999, rating: 4.4, category: "Men’s Sunglasses", image: "/src/assets/products/p354.jpg" },
{ id: "p355", name: "Burberry 4218 Jet Black Polarized", originalPrice: 10398, price: 6499, rating: 4.4, category: "Men’s Sunglasses", image: "/src/assets/products/p355.jpg" },
{ id: "p356", name: "Montblanc 0328 Silver Trim", originalPrice: 10398, price: 6499, rating: 4.3, category: "Men’s Sunglasses", image: "/src/assets/products/p356.jpg" },
{ id: "p357", name: "Dior Homme Black Tie 2.0", originalPrice: 11998, price: 7499, rating: 4.5, category: "Men’s Sunglasses", image: "/src/assets/products/p357.jpg" },
{ id: "p358", name: "Cartier Santos Aviator Gold", originalPrice: 12798, price: 7999, rating: 4.5, category: "Men’s Sunglasses", image: "/src/assets/products/p358.jpg" },
{ id: "p359", name: "Persol Steve McQueen Edition", originalPrice: 11198, price: 6999, rating: 4.4, category: "Men’s Sunglasses", image: "/src/assets/products/p359.jpg" },
{ id: "p360", name: "Ray-Ban Aviator Classic Gold Lens", originalPrice: 10398, price: 6499, rating: 4.4, category: "Men’s Sunglasses", image: "/src/assets/products/p360.jpg" },

// Ladies Sunglasses (Updated)
{ id: "p371", name: "Burberry WMNS 2138 Black Frame", originalPrice: 7998, price: 4999, rating: 4.4, category: "Ladies Sunglasses", image: "/src/assets/products/p371.jpg" },
{ id: "p372", name: "Cartier Day Night Wood-Gold Diamond", originalPrice: 9598, price: 5999, rating: 4.5, category: "Ladies Sunglasses", image: "/src/assets/products/p372.jpg" },
{ id: "p373", name: "Celine 1006 Silver Frame", originalPrice: 7998, price: 4999, rating: 4.4, category: "Ladies Sunglasses", image: "/src/assets/products/p373.jpg" },
{ id: "p374", name: "Celine 1031 Gold Frame", originalPrice: 7998, price: 4999, rating: 4.4, category: "Ladies Sunglasses", image: "/src/assets/products/p374.jpg" },
{ id: "p375", name: "Louis Vuitton 1502 Ice Day", originalPrice: 7998, price: 4999, rating: 4.4, category: "Ladies Sunglasses", image: "/src/assets/products/p375.jpg" },
{ id: "p376", name: "Marc Jacobs 503 Gold Frame", originalPrice: 7998, price: 4999, rating: 4.3, category: "Ladies Sunglasses", image: "/src/assets/products/p376.jpg" },
{ id: "p377", name: "Marc Jacobs 8831 Tiger Frame", originalPrice: 7998, price: 4999, rating: 4.3, category: "Ladies Sunglasses", image: "/src/assets/products/p377.jpg" },
{ id: "p378", name: "Marc Jacobs 9179 Water Day", originalPrice: 7998, price: 4999, rating: 4.4, category: "Ladies Sunglasses", image: "/src/assets/products/p378.jpg" },
{ id: "p379", name: "Prada WMNS 018 Gold Cream Frame", originalPrice: 9598, price: 5999, rating: 4.5, category: "Ladies Sunglasses", image: "/src/assets/products/p379.jpg" },
{ id: "p380", name: "Ray-Ban 3674 Black Frame", originalPrice: 7998, price: 4999, rating: 4.4, category: "Ladies Sunglasses", image: "/src/assets/products/p380.jpg" },
{ id: "p381", name: "Ray-Ban Aviator 3026 Silver Day Night", originalPrice: 7998, price: 4999, rating: 4.4, category: "Ladies Sunglasses", image: "/src/assets/products/p381.jpg" },
{ id: "p382", name: "Tom Ford 184 Black Frame", originalPrice: 7998, price: 4999, rating: 4.4, category: "Ladies Sunglasses", image: "/src/assets/products/p382.jpg" },
{ id: "p383", name: "Tom Ford 259 Black Frame", originalPrice: 7998, price: 4999, rating: 4.4, category: "Ladies Sunglasses", image: "/src/assets/products/p383.jpg" },
{ id: "p384", name: "Versace 234 Gold Frame", originalPrice: 7998, price: 4999, rating: 4.4, category: "Ladies Sunglasses", image: "/src/assets/products/p384.jpg" },

// Additional premium models (auto-filled)
{ id: "p385", name: "Gucci GG0894S Crystal Gold", originalPrice: 9598, price: 5999, rating: 4.5, category: "Ladies Sunglasses", image: "/src/assets/products/p385.jpg" },
{ id: "p386", name: "Dior SoReal Pop Blue Mirror", originalPrice: 9598, price: 5999, rating: 4.5, category: "Ladies Sunglasses", image: "/src/assets/products/p386.jpg" },
{ id: "p387", name: "Fendi FF0436 Brown Gold", originalPrice: 8798, price: 5499, rating: 4.3, category: "Ladies Sunglasses", image: "/src/assets/products/p387.jpg" },
{ id: "p388", name: "Chanel 5422Q Quilted Edition", originalPrice: 10398, price: 6499, rating: 4.5, category: "Ladies Sunglasses", image: "/src/assets/products/p388.jpg" },
{ id: "p389", name: "Prada PR01VS Rose Gold", originalPrice: 9598, price: 5999, rating: 4.4, category: "Ladies Sunglasses", image: "/src/assets/products/p389.jpg" },
{ id: "p390", name: "Louis Vuitton My Fair Lady Pink", originalPrice: 9598, price: 5999, rating: 4.5, category: "Ladies Sunglasses", image: "/src/assets/products/p390.jpg" },
{ id: "p391", name: "Michael Kors Adrianna II", originalPrice: 8798, price: 5499, rating: 4.4, category: "Ladies Sunglasses", image: "/src/assets/products/p391.jpg" },
{ id: "p392", name: "Fossil Keely Round Frame", originalPrice: 7998, price: 4999, rating: 4.3, category: "Ladies Sunglasses", image: "/src/assets/products/p392.jpg" },
{ id: "p393", name: "Tory Burch Pilot Brown", originalPrice: 7998, price: 4999, rating: 4.3, category: "Ladies Sunglasses", image: "/src/assets/products/p393.jpg" },
{ id: "p394", name: "Gucci 4228 Butterfly Gradient", originalPrice: 9598, price: 5999, rating: 4.5, category: "Ladies Sunglasses", image: "/src/assets/products/p394.jpg" },
{ id: "p395", name: "Ray-Ban Erika Velvet Edition", originalPrice: 7998, price: 4999, rating: 4.4, category: "Ladies Sunglasses", image: "/src/assets/products/p395.jpg" },
{ id: "p396", name: "Versace Medusa Chainlink Rose", originalPrice: 10398, price: 6499, rating: 4.5, category: "Ladies Sunglasses", image: "/src/assets/products/p396.jpg" },
{ id: "p397", name: "Prada PR07US Cat Eye", originalPrice: 9598, price: 5999, rating: 4.4, category: "Ladies Sunglasses", image: "/src/assets/products/p397.jpg" },
{ id: "p398", name: "Cartier Panthère de Cartier", originalPrice: 11198, price: 6999, rating: 4.6, category: "Ladies Sunglasses", image: "/src/assets/products/p398.jpg" },

// Frames Section (Updated)
{ id: "p401", name: "Ray-Ban 3674 Black Frame", originalPrice: 7998, price: 4999, rating: 4.5, category: "Frames", image: "/src/assets/products/p401.jpg" },
{ id: "p402", name: "Ray-Ban Aviator 3026 Silver Day Night", originalPrice: 7998, price: 4999, rating: 4.4, category: "Frames", image: "/src/assets/products/p402.jpg" },
{ id: "p403", name: "Tom Ford 184 Black Frame", originalPrice: 7998, price: 4999, rating: 4.4, category: "Frames", image: "/src/assets/products/p403.jpg" },
{ id: "p404", name: "Tom Ford 259 Black Frame", originalPrice: 7998, price: 4999, rating: 4.4, category: "Frames", image: "/src/assets/products/p404.jpg" },
{ id: "p405", name: "Versace 234 Gold Frame", originalPrice: 7998, price: 4999, rating: 4.5, category: "Frames", image: "/src/assets/products/p405.jpg" },

// Additional Frames (filled to p414)
{ id: "p406", name: "Gucci GG0061O Transparent Rose Frame", originalPrice: 8798, price: 5499, rating: 4.3, category: "Frames", image: "/src/assets/products/p406.jpg" },
{ id: "p407", name: "Prada VPR 17V Tortoise Frame", originalPrice: 7998, price: 4999, rating: 4.4, category: "Frames", image: "/src/assets/products/p407.jpg" },
{ id: "p408", name: "Burberry BE2345 Havana Frame", originalPrice: 8798, price: 5499, rating: 4.5, category: "Frames", image: "/src/assets/products/p408.jpg" },
{ id: "p409", name: "Michael Kors MK3035 Pink Gold Frame", originalPrice: 7998, price: 4999, rating: 4.3, category: "Frames", image: "/src/assets/products/p409.jpg" },
{ id: "p410", name: "Emporio Armani EA1105 Black Matte", originalPrice: 8798, price: 5499, rating: 4.5, category: "Frames", image: "/src/assets/products/p410.jpg" },
{ id: "p411", name: "Fossil FOS 7008 Blue Classic", originalPrice: 7998, price: 4999, rating: 4.2, category: "Frames", image: "/src/assets/products/p411.jpg" },
{ id: "p412", name: "Dior Homme 0224 Square Silver", originalPrice: 9598, price: 5999, rating: 4.5, category: "Frames", image: "/src/assets/products/p412.jpg" },
{ id: "p413", name: "Oakley OX8046 Crosslink Black", originalPrice: 8798, price: 5499, rating: 4.4, category: "Frames", image: "/src/assets/products/p413.jpg" },
{ id: "p414", name: "Cartier CT0353 Wood & Gold Frame", originalPrice: 11198, price: 6999, rating: 4.6, category: "Frames", image: "/src/assets/products/p414.jpg" },

];

export default MOCK_PRODUCTS;